### ISSUE TITLE
polymorphism at frequency of around 0.5 rejected

### ISSUE THREAD

**Issue by wmoebius** [barricklab/breseq#103]
First of all, thanks for developing and maintaining breseq!

Unless I'm missing something, I think breseq falsely rejects mutations in version 0.28.1. See this line from output.gd:

RA  371 .   NC_001604   7533    0   C   T   bias_e_value=9999.06    bias_p_value=0.250371   consensus_score=369.5   fisher_strand_p_value=0.813517  frequency=1 ks_quality_p_value=0.0833911    major_base=T    major_cov=794/642   major_frequency=5.43796062e-01  minor_base=C    minor_cov=672/532   new_cov=794/642 polymorphism_frequency=5.43796062e-01   polymorphism_score=inf  prediction=consensus    ref_cov=672/532 reject=FREQUENCY_CUTOFF total_cov=1468/1174

Only option used was '-p'. This mutation was called in version 0.25c.

More generally, we have anecdotal evidence that mutations in the 30-70% range are rejected but included in the output.gd file (as the one above).

**Comment by jeffreybarrick** [comment]
It looks like this error was due to some problems with how infinite polymorphism scores were being treated in the MacOSX compiled version (and possible in the source code compiled on other platforms). I believe that I've fixed the problem in the test release `breseq-0.28.2rc3`, which you can download from http://barricklab.org/release/breseq/
