### ISSUE TITLE
Switched to consensus mode even though polymorphism_frequency < threshold.

### ISSUE THREAD

**Issue by yeemey** [barricklab/breseq#107]
Hi Jeffrey,

Based on your response to this issue [https://github.com/barricklab/breseq/issues/94](url) I set my consensus threshold to be (1 - polymorphism threshold), as follows:

`breseq -p -o . -r $ref1 $ref2 --polymorphism-minimum-coverage-each-strand 5 --polymorphism-frequency-cutoff 0.01 --consensus-frequency-cutoff 0.99 $fastq1 $fastq2 $fastq3
`

This is the result that I got:
`RA	166	.	NC_002937	42867	1	.	G	bias_e_value=5434290	bias_p_value=1	consensus_score=207.5	fisher_strand_p_value=1	frequency=1	ks_quality_p_value=0.999184	major_base=G	major_cov=26/23	major_frequency=9.80004311e-01	minor_base=.	minor_cov=1/0	new_cov=26/23	polymorphism_frequency=9.80004311e-01	polymorphism_score=-2.5	prediction=consensus	ref_cov=1/0	reject=FREQUENCY_CUTOFF	total_cov=27/23
`

Breseq switched to using consensus prediction even though polymorphism_frequency is < 0.99. 
My guess is that since the polymorphism appears to be an insertion (based on IGV), the minor frequency = 0 and doesn't meet the 0.01 polymorphism frequency cutoff. However, even with --polymorphism-frequency-cutoff 0 (and all other settings the same as above), I get the exact same result.

I'm losing insertions that should've been called, but aren't because they don't meet the consensus threshold. Do you have suggestions for how to remedy this? 

(I'm using breseq 0.27.1)

Thank you!
Yee Mey

**Comment by jeffreybarrick** [comment]
Hi Yee Mey,

This polymorphism is being rejected (which means it gets changed to a consensus 100% prediction) for multiple reasons. 

First, it doesn't have a sufficient polymorphism_score (based on the probability model comparing the chances that you would see one variant read and the given number of consensus reads based on the normal chances of sequencing errors in your data set). The setting --polymorphism-score-cutoff controls this. You could set it extremely low (maybe -99999) if you want any time there is a variant read for the prediction to come through (not recommended though, see below).

Second, it does not meet the --polymorphism-minimum-coverage-each-strand requirement. By default, you must have 2 reads on both strands for the variant allele for breseq to predict it as a polymorphism. This one has one variant read on one strand and zero on the other strand (minor_cov=1/0).

If you want to turn off this filter, set:
--polymorphism-minimum-coverage-each-strand 0

If you are trying to get more (likely mostly false-positive) predictions may also want to turn off some other polymorphism filters:
--polymorphism-reject-indel-homopolymer-length 0
--polymorphism-reject-surrounding-homopolymer-length 0
* These might explain some "missing" indel polymorphisms.

The defaults are present so that you don't get a lot of false-positive polymorphisms. I'd be very careful in interpreting the results and you may get many many mutations predicted.

in the next version of breseq (v 0.28.1), it will keep some information in a REJECT_POLYMORPHISM field and also print it out in the HTML output when you click on a prediction to let you know why it was reassigned from a polymorphism to a consensus prediction (i.e., which filter it failed).

**Comment by yeemey** [comment]
OK, so although this polymorphism occurs with high frequency, there's a good probability that it's a sequencing error, and it didn't occur on both strands. I was misled by the reject=FREQUENCY_CUTOFF, since it actually refers to frequency on each strand, not polymorphism frequency.

Yes, the feature to note which filter(s) it failed will be very helpful indeed. Thank you for your response!
