### ISSUE TITLE
R plot error

### ISSUE THREAD

**Issue by meono** [barricklab/breseq#120]
Hi,
I am currently having an issue with one of my runs that returns the following error:
```[system] R --vanilla < /home/user/programs/breseq-0.30.0-Linux-x86_64/bin/../share/breseq//coverage_distribution.r > ./07_error_calibration/4.unique_only_coverage_distribution.tab.r.log distribution_file=./07_error_calibration/4.unique_only_coverage_distribution.tab plot_file=./output/calibration/4.unique_coverage.pdf deletion_propagation_pr_cutoff=0.001165
Warning messages:
1: In nlm(f_nb, c(mean_estimate, try_size), iterlim = 1000, print.level = this.print.level) :
  NA/Inf replaced by maximum positive value
2: In nlm(f_nb, c(mean_estimate, try_size), iterlim = 1000, print.level = this.print.level) :
  NA/Inf replaced by maximum positive value
3: In nlm(f_nb, c(mean_estimate, try_size), iterlim = 1000, print.level = this.print.level) :
  NA/Inf replaced by maximum positive value
Warning messages:
1: In nlm(f_p, c(m), print.level = this.print.level) :
  NA/Inf replaced by maximum positive value
2: In nlm(f_p, c(m), print.level = this.print.level) :
  NA/Inf replaced by maximum positive value
Error in plot.window(...) : need finite 'ylim' values
Calls: plot -> plot.default -> localWindow -> plot.window
Execution halted
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] R --vanilla < /home/user/programs/breseq-0.30.0-Linux-x86_64/bin/../share/breseq//coverage_distribution.r > ./07_error_calibration/4.unique_only_coverage_distribution.tab.r.log distribution_file=./07_error_calibration/4.unique_only_coverage_distribution.tab plot_file=./output/calibration/4.unique_coverage.pdf deletion_propagation_pr_cutoff=0.001165
Result code: 256
FILE: libbreseq/common.h   LINE: 1384
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

I am using R 3.3.3 but also tried with R 3.3.1. I thought `--brief-html-output` could skip this part but apparently not. Any advice on how to proceed?

Thanks!

**Comment by jeffreybarrick** [comment]
This error is related to fitting the coverage distribution of reads across the genome. It happens before the output step. 

You could try running _breseq_ with the --targeted-sequencing option so that it will not fit this coverage distribution, but this will also make it so _breseq_ does not call deletion mutations.

 I think probably there is something wrong with the sequencing data for this sample and it has very low or very biased coverage of the reference genome. If you are willing share the input files and command line with me from the failed run, that would be great. Then I could at least make sure it gives a more informative error or falls back to a mode that works. If you email me at the address in the breseq header I can give you access to a shared folder to upload the data files.

Thanks!

**Comment by meono** [comment]
Thanks a lot for the quick response.
I've checked with our PI and unfortunately I can not share the run details. However, after your comment, I tried limiting the number of reads (~1/4 and ~3/4) or using `--limit-fold-coverage 150` with all reads. All three worked without the error and a rough check so far reveals same results. What looked unusual with the sample was an overrepresentation of ~60kb region (multiple copies should be present with the strain now), an already high overall coverage (>250X) and missing coverage for an insert (presented as a separate reference file).
