### ISSUE TITLE
Breseq interrupted during "Resolving alignments with junction candidates" process

### ISSUE THREAD

**Issue by sleyn** [barricklab/breseq#121]
Hi!

I have series of samples from evolution experiment sequenced on Illumina NextSeq. On some samples Breseq works fine but on others I've observed that it simply stoped during "Resolving alignments with junction candidates" process. On logs I see on errors. It just stoped on something like:

"   ...
    READS:2470000
    READS:2480000
    READS:2490000
    READS:2500000
    READS:2510000
    READS:2520000
    READS:2530000
    READS:2540000
    READS:2550000
    READS:2560000"

Could you give an advise how to find a cause?

**Comment by jeffreybarrick** [comment]
Did it have a seg fault or just remain there without returning a prompt?
It's possible that _breseq_ still working and just needs longer on this dataset for that step.

**Comment by sleyn** [comment]
I've installed the latest 0.30 version (I had 0.28 before). Now breseq produces an error:

"...
 READ FILE:22-AO-D4_S22_L004_R2_001_single_1
    READS:49830000
    READS:49840000
[system] rm -f ./01_sequence_conversion/22-AO-D4_S22_L001_R1_001_1.converted.fastq
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] rm -f ./01_sequence_conversion/22-AO-D4_S22_L001_R1_001_1.converted.fastq
Result code: -1
FILE: libbreseq/common.h   LINE: 1384
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
"

**Comment by jeffreybarrick** [comment]
Did you start the run with the new breseq version in a "clean" directory (with no 0*, data, or output directories in it), so that the new version of breseq starts at step 1?

**Comment by sleyn** [comment]
Yes, I've deleted every directory that Breseq created from the last run and restarted it. Everything is the same.

**Comment by jeffreybarrick** [comment]
If you're willing to share the input files with me to see if I can reproduce the bug, contact me at the email in the breseq header and I will give you a place to upload them. Thanks.

**Comment by jeffreybarrick** [comment]
Is it possible that you are running out of hard drive space during these runs? The files are fairly large?

**Comment by sleyn** [comment]
I have 2Tb more disk space. However the samples that passed Breseq indeed have less file size.

Semen

**Comment by jeffreybarrick** [comment]
OK, I figured out what is going on! You have a lot of very, very short trimmed "reads" in your input. Many have ≤6 bases. These can be aligned to some junction sequences and _breseq_ has to track all of those possibilities, so it causes it to need a ton of RAM. It took me a machine with >64 GB RAM to get the run to complete. It may be stalling because it is thrashing virtual memory on your machine.

You could remove those short reads from your FASTQ input files (safest), or try running _breseq_ with adding this option (or even a value bigger than 12). I think that will get it to ignore those reads at an early enough stage that they don't cause things to explode.

--require-match-length 12

I will make it so a future version of _breseq_ ignores very short reads unless specifically the user specifies not to (since they are generally useless).

**Comment by sleyn** [comment]
Thank you very much, Jeff!

Indeed - files have a lot of very short reads. It is strange why it was happend. I’ve processed them with trimmomatic with MINLEN:65 option…

I’ll look again on my trimming process.

Thanks,
Semion

**Comment by jeffreybarrick** [comment]
v0.30.1 implements default filtering of reads ≤18 base pairs which makes it possible to reasonably process this dataset.
