### ISSUE TITLE
IS insertions when using FASTA reference + GFF3 annotation are not predicted mutations

### ISSUE THREAD

**Issue by dannagifford** [barricklab/breseq#124]
When I run breseq (0.30.0) with a FASTA reference + GFF3 annotation from NCBI, IS insertions do not get incorporated into the Predicted Mutations table, and instead remain as pairs of Unassigned Junctions. Running with a GenBank (Full) reference instead does include them as Predicted Mutations.
Perhaps this is intended and is an issue with the GFF3 format?  I will run with GenBank references from now on, but it might be handy to mention this somewhere (otherwise saps like me will try to resolve them manually...).

breseq -l 30 --reference NC_000913.3.fa --reference NC_000913.3.gff --cnv --name A5_ins_test --output BRESEQ/. \`ls FASTQ/*fastq.gz\`

[NC_000913.3.zip](https://github.com/barricklab/breseq/files/1095437/NC_000913.3.zip)

Test FASTQs (with an IS2 insertion) http://137.205.68.130/public/researcher/FASTQ.zip

**Comment by dannagifford** [comment]
GenBank (Full)
[NC_000913.3.gb.zip](https://github.com/barricklab/breseq/files/1095450/NC_000913.3.gb.zip)

**Comment by jeffreybarrick** [comment]
Thanks for the usage note. It seems like the NCBI conversion to GFF is putting the information about IS elements in a very idiosyncratic, uninformative way into the file with lines like this:

`NC_000913.3	RefSeq	region	15387	16731	.	+	.	ID=id2;gbkey=mobile_element
`

_breseq_ will recognize IS elements annotated in GFF format if the main tag is `mobile_element` or `repeat_region`  (instead of the generic `region` used here). The `name=` or `label=` descriptive field should also be the name of the IS element family. 

This seems like a bit of a special case for me to add into the normal _breseq_ code since the corresponding GenBank file from NCBI is fine, but let me know if its super-annoying to you and I will see what I can do!

**Comment by dannagifford** [comment]
Yes it is a bit too specific---it seems like some of the genomes are a mess, as the BW25113 genome is also missing some mobile_element annotations. Not really your problem!  Seems like the best solution would be to use good annotations...
