### ISSUE TITLE
Question about how breseq calculates depth of coverage

### ISSUE THREAD

**Issue by dixonfitzhume** [barricklab/breseq#151]
I get different results in terms of coverage when I try to (roughly) recreate the output.vcf file in the data folder that breseq outputs (using the command below). I'm looking at a specific positions in one of my contigs (defined in position_list.txt). This includes some positions that breseq found to have SNPs.  

samtools mpileup -ug -l ~/position_list.txt -f reference.fasta -d $max_depth -Q 2 -t AD,INFO/AD,DP reference.bam | bcftools call -mA -Ov --ploidy 1 -o isol.vcf 

With this, I get roughly the same number of reads for each ALT base (defined in the AD tag), but my depth (DP tag) is off by ~10-100 reads when comparing these results to breseq's. Is there a way that I can back out how breseq calculated what the coverage/read depth is at a given position?  The coverage.tab files add up to my samtools output and so not what I see in my output.vcf from breseq. I'm interested in calculating the frequencies at SNPs that don't pass breseq's 5% frequency filter - I don't see them in the 'RA' section of output.gd file, and I'd like to get a measure of the read depth at these positions in a way comparable to how breseq calculated it.

**Comment by jeffreybarrick** [comment]
This discrepancy is probably mainly due to _breseq_ ignoring some aligned bases at the ends of reads (end trimming, which is explained [here in the manual](http://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/methods.html#read-end-trimming)). 

There could also be some additional discrepancies between the **mpileup** and _breseq_ output due to the way that _breseq_ handles reads that map multiple locations equally well. It will include multiple BAM entries for them, but they will be skipped in calculating the stats about a SNP. 

_breseq_ marks both of these pieces of information in aux fields in the BAM entries, but **mpileup** won't know how to use this information.

If you'd like _breseq_ to output complete information about variants that have a lower frequency, you can set **--polymorphism-frequency-cutoff** to a lower value or even zero. You may also want to set some of the other values in the "Polymorphism Read Alignment (RA) Evidence Options" section of the help to lower values.
