### ISSUE TITLE
question about concatenating data from multiple genbank files

### ISSUE THREAD

**Issue by ct1219** [barricklab/breseq#152]
I'm working with seq data from a species that has a chromosome and a plasmid, and to keep things simple I ran breseq twice for each sample that I had, as the genbank files for each are separate. I'd now like to make a phylogeny with the gdtools/phylip option, but I'd like to find some way of merging both the chromosome and plasmid data so that they're both reflected in the tree - is there a way to do this? I tried simply concatenating the gbk files/gd files together but received errors in both cases.

**Comment by jeffreybarrick** [comment]
Two possible solutions:

(1) Recommended: Re-run _breseq_ providing both reference files to one run. Just supply the reference option twice and you can use both files (Ex: `-r chr.gbk -r plasmid.gbk`. This is the preferred method because some read mismapping to the wrong reference can occur when you map to only one reference at a time in two separate runs.

(2) Alternative Method: Use `gdtools UNION` to combine each plasmid/chromosome combination into a single GD file. When you use further GD commands (like `gdtools ANNOTATE` to create a PHYLIP input file), provide both reference sequences using the `-r` option (as above).

**Comment by ct1219** [comment]
Thank you!

**Comment by jeffreybarrick** [comment]
Sure thing.
