### ISSUE TITLE
configure file not present in the distribution

### ISSUE THREAD

**Issue by lguy** [barricklab/breseq#154]
The configure file, which would be useful for installation (see http://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/installation.html#installing-in-a-system-wide-location), is listed in .gitignore and thus not present in the source archive. It would be useful to have it shipped with the source code.

**Comment by lguy** [comment]
Looking further it might seem it's the documentation that might require an update. Using autoconf worked (after some effort), but it would be nice to see it documented.

**Comment by jeffreybarrick** [comment]
It is a little confusing, but there are two versions of the "source code":

1. There's the "source code package" which you get if you download a release version. This has the configure script included. The "Method 2. Source code package" instructions in the manual are for using this version.

2. There's the "development source code" which is what you get if you clone the GitHub repository. There's a short note about this in the manual under "Method 3. Development source code" , but the instructions for using this are hidden in the DEVELOPER file that is checked into the repository, since this is sort of meant for more experienced coders (who have autoconf installed on their system, for example). We prefer to not check the configure script directly into the repository.

We'll add a clarification to the manual that Method 3 is for the "GitHub source code" so that it is easier to find.

Thanks!
