### ISSUE TITLE
BaseRecalibrator

### ISSUE THREAD

**Issue by UWBCoevolution** [barricklab/breseq#160]
Hi, I am using breseq for population genomic data. I am currently comparing the process with GATK, and have a question.
With GATK, we have to call "baserecalibrator" as a preprocess for fastq file. I am wondering if breseq do "baserecalibrator" as a preprocess. If it does, what file is used to provide as a "true mutation" data? Is there an option that we can specify the file? 
Please let me know.
Thank you.

**Comment by jeffreybarrick** [comment]
There is no analogous step or input in _breseq_. It does "recalibrate" base error rates from the input FASTQ as part of its pipeline internally, by assuming that most differences from the reference genome in reads are sequencing errors rather than true genetic variants, which is true when you are re-sequencing a genome and have a close reference sequence.
