### ISSUE TITLE
"de novo assembled reference genome"

### ISSUE THREAD

**Issue by ss-91** [barricklab/breseq#165]
Hi,
 I have just started using breseq (and it's a great pipeline). I am analyzing a lab evolution experiment. 

It seems that my ancestor strain has a lot of genetic variants compared to the reference genome. To remove the ancestral mutations from the evolved bacteria, I originally used gdtools SUBTRACT.

However, I wanted to try de novo assembling my own reference genome using reads from the ancestor(they had a bout 40-fold coverage when mapped to reference genome)  Running our ancestor fasta file with de novo assembled reference still detected many mutations even though we assume there should have been none. I assume that this is due to poor assembly and breseq being sensitive?
Do you have any insight on this issue we are facing?

**Comment by vr1087** [comment]
It's hard to say with out more details, but I would check that these high number of variants are not due to biological contamination, which can significantly increase the false positive mutation prediction rate. Breseq assumes no biological contamination in the sample and, as such, will map reads from closely related organisms to your reference sequence. Also, note a caveat of the SUBTRACT function. This operation actually subtracts variant frequencies and not just the identity of the mutations. See my bug report 'gdtools set operation bug'.
