### ISSUE TITLE
No values loaded into log10 prob table

### ISSUE THREAD

**Issue by korinalb** [barricklab/breseq#168]
Hi,

I'm running into the following error running breseq on my school's computing cluster:

```
--- ALREADY COMPLETE Read and reference sequence file input
--- ALREADY COMPLETE Read alignment to reference genome
--- ALREADY COMPLETE Preprocessing alignments for candidate junction identification
--- ALREADY COMPLETE Preliminary analysis of coverage distribution
--- ALREADY COMPLETE Identifying junction candidates
--- ALREADY COMPLETE Re-alignment to junction candidates
--- ALREADY COMPLETE Resolving alignments with junction candidates
--- ALREADY COMPLETE Creating BAM files
--- ALREADY COMPLETE Tabulating error counts
--- ALREADY COMPLETE Re-calibrating base error rates
+++   NOW PROCESSING Examining read alignment evidence
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
No values loaded into log10 prob table.
FILE: error_count.cpp   LINE: 918
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Does anyone know what I can do to fix this? I can't find a reference to this in a previous issue.

 Thanks!
Korin
breseq/0.30.0
R/3.3.1
bowtie2/2.1.0

**Comment by jeffreybarrick** [comment]
Can you post or send the file `07_error_calibration/error_rates.tab`?

This error seems to indicate that you have absolutely no reads aligned to the reference, or no discrepancies from the genome in those reads. Is that possible? Or maybe this file is missing?

**Comment by jeffreybarrick** [comment]
Is this Illumina data or from a different sequencing method? 

Maybe none of your reads are mapping? This could potentially happen if you have long barcodes or adaptor sequences left on all of your reads, or if they are from some of the sequencing technologies that are "messier" as far as the ends of reads. _breseq_ requires 90% of the length of a read to map by default. You can use `--require-match-fraction 0` and see what happens if you suspect this could be the problem (be sure to first delete the output so every step runs again).

If this isn't it and you are willing to share your input files for me to take a look, contact me at the email in the _breseq_ header.
