### ISSUE TITLE
Interpretation of the unassigned junction table

### ISSUE THREAD

**Issue by satkinson0115** [barricklab/breseq#170]
Hello,

I'm struggling to understand the unassigned junction table. I've been using the Clonal tutorial as a guide and the section 4.A is still unclear. 

The reason I'm confused is because the tutorial image doesn't look like the REL606 reference on NCBI and it makes the mutated genome look like a duplication (two red arrows, with the second having the same start and end postition):

![](http://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/_images/ZDB83.rnk-citG.JC.schematic.png)

When I look at this region using NCBI's graphics view it looks like this:
![screen shot 2018-08-17 at 1 31 15 pm](https://user-images.githubusercontent.com/13423509/44282924-40875980-a222-11e8-8287-f5198d6c8af2.png)

Does this mean that the region between the green and the blue line has been deleted in this sample (thereby removing the _rna_ and _citT_ genes and fusing _rnk_ and _citG_ together)?

Also, why does the second arrow in the tutorial image only have one coordinate, 625889? Is this a typo? But the figure also shows "more copies?"?  What would imply more copies in this instance?

I want to make sure I understand the example data before trying to interpret my own data.

Thanks for any help you can give,
Samantha

**Comment by jeffreybarrick** [comment]
Hi Samantha,

There *is* a problem with the labeling of coordinates in the figure in the manual. (Thanks for catching that!) Here is the corrected version:

![zdb83 rnk-citg jc schematic](https://user-images.githubusercontent.com/6777876/44828292-de910180-abdc-11e8-9541-6ac5a361b601.png)

This figure is explaining that the mutated genome (the one with short-read resequencing data) has a new junction between two copies of a segment of the reference genome that is formed between the two duplicated regions (red arrows).

The genome browser view looks different because the arrows in the figure are genome segments and the arrows in the browser are genes. The red segment in the figure extends from within the _citG_ gene to within the _rnk_ gene.

Does that make sense?

**Comment by jeffreybarrick** [comment]
Your figure is correct in showing what the junction predicts exists in the sequenced genome!

The estimated frequency of the junction would be ~50% if it were a duplication (meaning there are as many reads for the JC in your figure as there are for the "normal" junctions overlapping left and right sides of the red segment in the sequenced sample). Your frequency is quite a bit higher, which may mean that there are multiple JC copies per end. This could happen if there were 3-4 consecutive copies of the red segment end-to-end, as would happen in a triplication or quadruplication of the red segment.

You can look at the read depth coverage overlapping the red segment positions to get some confirmation of the copy number of the duplication/amplification (using the breseq bam2cov subcommand or inputing the BAM files and reference from the "data" folder into a browser like IGV).

If this were a "short deletion, insertion, substitution, or tandem amplificatios" you might see "read alignment" (RA) evidence because the read would be able to map across the mutation if the change in the reference genome is small, or _breseq_ automatically calls a mutation if the size of the duplication is shorter than the read length b/c there is less danger of having a false positive in these cases than for these predictions of very large duplications from JC evidence in our experience.

**Comment by SamanthaNicole** [comment]
Hello,

I have a follow up question about using the read depth to estimate the copy number. I was able to produce a coverage graph of the region using the BAM2COV subcommand and the coverage of that region averages about 500:

![cp002621 970000-1010000](https://user-images.githubusercontent.com/13423509/45243714-859b2a80-b2ba-11e8-82d0-97f15ffc2a47.png)

I'm unsure how to interpret this to determine what the copy number would be. Is it a ratio where a coverage of 500 would estimate 5 copies? 

Thanks,
Samantha

**Comment by jeffreybarrick** [comment]
Yes, if the average coverage is ~100x for your sample and there is a read depth coverage of ~500x over the amplified region, then there are likely 5 copies of that region in the sequenced genome. Since coverage can be very noisy across a region (as you can see) and amplification can be unstable (such that come cells in the population may evolve fewer or additional copies at a high rate) I'd consider this a rough estimate. The junction "new" and old" coverage can provide another estimate to corroborate the coverage estimate.
