### ISSUE TITLE
The RA alignments in evidence tab do not tally with IGV alignments

### ISSUE THREAD

**Issue by Ramya1000** [barricklab/breseq#173]
Hello,

I am running breseq in consensus mode and was manually verifying the variants called using IGV. At a particular position I found 85 reads were supporting the reference base 'G' whereas 5 reads were supporting an alternate base 'A'. Still Breseq had called it as a consensus call with 'A'. On closer inspection, I observed that both output.gd as well as RA evidence for that position (by clicking on evidence in index html table), breseq is somehow only showing the 5 reads supporting 'A' whereas the rets of 85 reads are not considered. I am attaching snapshots of both RA evidence and IGV of the same region for ease of understanding.

Thanks,
R
![ra_evidence_chr04_987245](https://user-images.githubusercontent.com/43824050/46427555-ba5e9e00-c70f-11e8-87e1-f7003fef189a.png)
![igv_chr04_987245](https://user-images.githubusercontent.com/43824050/46427586-cea29b00-c70f-11e8-96dc-e3aabd5a84c3.png)

**Comment by jeffreybarrick** [comment]
Probably the other reads are not being counted because they align equally well at multiple repetitive sites in the genome, but the reads with the "A" variant extend to the left side far enough for them to be unambiguously assigned to this position.

_breseq_ adds a SAM flag (X1:i:#of times read has equally good alignments) to the reads that are redundantly mapped, but IGV doesn't know about this so it shows all of the reads as if they are equally good evidence for a variant. (You might be able to hover your mouse over the reads and see the X1 tag value.)

You can further investigate whether this is the right explanation by using `breseq BAM2ALN` to draw an alignment of the region. If you include the `-r` option, it will show the repeat-mapped reads (as IGV does). If you do not (default), those won't show up.

**Comment by Ramya1000** [comment]
Thank you so much for the prompt reply, I really appreciate it. You are absolutely correct! I hovered the mouse over IGV and found that the rest of the reads mapped equally well elsewhere too. Btw, the -r option of bam2aln is used for specifying a region. I could not find an option (on a quick search) to get the repeat reads included. Thanks, Ramya
