### ISSUE TITLE
Differences in predicted mutation between consensus mode and polymorphism mode (100% frequency)

### ISSUE THREAD

**Issue by Selveshwari** [barricklab/breseq#196]
I passed my sample through both consensus and polymorphism mode. There are differences in predicted mutations when comparing the consensus mode and the 100% mutations in polymorphism mode. The mutations predicted are the same but the location of the mutation is different between the two modes. Additionally there are two mutations that are predicted by the consensus mode which is not present in the polymorphism mode. Can you please explain why this is happening and if it is to be expected. I am attaching a table showing the differences.

Consensus position | mutation | annotation | gene |   | Polymorphism position | mutation | freq | annotation | gene
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
629,992 | (TCAAC)1→2 | coding (99/2106 nt) | cstA → |   | 629,987 | +TCAAC | 100% | coding (94/2106 nt) | cstA →
2,111,259 | Δ1 bp | coding (718/900 nt) | rfbD ← |   | 2,111,256 | Δ1 bp | 100% | coding (721/900 nt) | rfbD ←
2,173,363 | Δ2 bp | pseudogene (915‑916/1358 nt) | gatC ← |   | 2,173,361 | Δ2 bp | 100% | pseudogene (917‑918/1358 nt) | gatC ←
2,724,952 | +A | coding (795/1299 nt) | kgtP ← |   | 2,724,951:1 | +A | 100% | coding (796/1299 nt) | kgtP ←
2,814,459 | Δ1 bp | coding (275/516 nt) | luxS ← |   | 2,814,458 | Δ1 bp | 100% | coding (276/516 nt) | luxS ←
3,560,455 | +G | pseudogene (151/758 nt) | glpR ← |   | 3,560,455:1 | +G | 100% | pseudogene (151/758 nt) | glpR ←
3,638,536 | Δ1 bp | coding (895/1500 nt) | pitA → |   | 3,638,535 | Δ1 bp | 100% | coding (894/1500 nt) | pitA →
3,815,883 | +C | coding (667/687 nt) | rph ← |   | 3,815,879:1 | +C | 100% | coding (671/687 nt) | rph ←
3,938,441 | Δ1 bp | coding (215/993 nt) | rbsR → |   | 3,938,440 | Δ1 bp | 100% | coding (214/993 nt) | rbsR →
4,296,381 | +GC | intergenic (+587/+55) | gltP → / ← yjcO | 4,296,380:1 | +CG | 100% | intergenic (+586/+56) | gltP → / ← yjcO
3,207,549 | Δ1 bp | coding (179/606 nt) | ttdB → |   |   |   |   |   |  
4,591,397 | +GT | intergenic (‑118/‑260) | btsT ← / → tsr |   |   |   |   |

**Comment by jeffreybarrick** [comment]
These mutations are in homopolymers or small repeats such as `GCGCGCG` that add or subtract a unit of the repeat.

**In consensus mode:**_breseq_ "normalizes" the positions of these mutations by shifting them to the highest coordinate possible of the many equivalent ways of describing them (adding `GC` at multiple sites would give the same evolved sequence) `gdtools normalize` describes this process and can perform it on an already existing GenomeDiff file.

**In polymorphism mode:** _breseq_ does not shift the mutations because this sometimes results in two different mutations overlapping because they could be at 20% and 50% of the population, for example. The logic to figure this out is not trivial and will probably have to wait for an improvement in local multiple read alignment to polish the aligned reads before predicting mutations.

For now, perhaps it would be useful to you to have an option to skip the normalization step in consensus mode? It also won't guarantee these are always predicted at the same locations due to some differences in the way `bowtie2` will sometimes align different reads, but it would probably mostly correspond.
