### ISSUE TITLE
meta data present in output.gd not being copied to annotated.gd file

### ISSUE THREAD

**Issue by danieldeatherage** [barricklab/breseq#197]
meta data present in output.gd such as listed below is not present in evidence/annotated.gd file. True in both polymorphism and clonal mode, have not tested with using input.gd file with -g option

#=CREATED	
#=PROGRAM	
#=COMMAND	
#=REFSEQ	
#=READSEQ
#=CONVERTED-BASES	
#=CONVERTED-READS
#=INPUT-BASES
#=INPUT-READS
#=MAPPED-BASES
#=MAPPED-READS

**Comment by jeffreybarrick** [comment]
This is fixed in the newest version in the repository for the next release.

Two notes:

* You should only rely on the version of `annotated.gd` located in the `data` folder. The one located under `output/evidence/annotated.gd` is purposefully hidden so that it can be stripped of some information and used by the consistency tests.
* All of this metadata information and much more is now available in the `data/summary.json` file.
