### ISSUE TITLE
Deletions that span start of reference file not being called

### ISSUE THREAD

**Issue by danieldeatherage** [barricklab/breseq#199]
hypothetical 10kb plasmid with 5kb deletion starting at 7kb passes 10kb/0 and continues to 2kb is only called as an unassigned junction, not deletion. 

confusion about how this should be represented (ie 5000 bp deletion starting at 7000 or 2kb deletion starting at 1, and 3kb deletion starting at 7000).

can provide test files if desired

**Comment by jeffreybarrick** [comment]
It shouldn't be too hard for _breseq_ to get this right. I'll see what I can do.

No need to send the test data, I can add this situation to one of the consistency tests.

Since DEL entries have a start position and a size, your situation would show up in the GenomeDiff file as one 5000 bp deletion starting at 7000. That way it would correctly be counted as one deletion.

**Comment by jeffreybarrick** [comment]
I have some code that should be able to accomplish this now. On second thought, it would be helpful if you can give me a real test case.

**Comment by jeffreybarrick** [comment]
This new functionality was added in v0.43.0 and several test cases were added to the repository.
