### ISSUE TITLE
Problems with gbk files from prokka 

### ISSUE THREAD

**Issue by muzzial1** [barricklab/breseq#242]
Dears, I've recently moved from v.0.27 to v.0.35.1. It's a quite jump, still learning new features, thanks for the great job you did! Unfortunately, I noticed that now breseq requires a stricter gbk reference file that usually is very difficult to get from annotation pipelines (prokka for example) and in any case it's difficult to use it with historical datasets if already annotated.
I noticed a couple of errors in parsing the header of the following raw gbk file, that the previous version of breseq was capable to use. Now breseq seems to get the length of the genome from the first line (not from the ‘source’ field) but this is risky (and it doesn't' work, in this example, the reason is the ‘_’, prokka did it…). Another problem is that the ‘Seq id’ is derived from ‘ACCESSION’ or ‘VERSION’ headers that are empty in gbk files from the prokka pipeline. Considering this couple of problems, I’m also worried that now breseq will have some difficulties to parse concatenated gbk files (that you can get from the annotation of not closed genomes that are at contig level). I hope you could help me to solve these issues, thanks.

LOCUS       gi_99999999_gb_AE000000.1_2150000 bp   DNA linear       15-JUN-2020
DEFINITION  Neisseria lactamica strain ABC.
ACCESSION
VERSION
KEYWORDS    .
SOURCE      Neisseria lactamica
  ORGANISM  Neisseria lactamica
            Unclassified.
COMMENT     Annotated using prokka 1.13.3 from
            https://github.com/tseemann/prokka.
FEATURES             Location/Qualifiers
     source          1..2150000

**Comment by jeffreybarrick** [comment]
I guess it's a little unclear what to do here.

To me, it looks like you have an incorrectly formatted GenBank LOCUS line with an underscore where there should be whitespace, and ACCESSION and VERSION are supposed to be defined in GenBank files, so Prokka is not outputting a valid GenBank file.

I'm basing that on the GenBank file format description here:
https://www.ncbi.nlm.nih.gov/Sitemap/samplerecord.html

And also what you get when you download a bacterial genome from GenBank:
https://www.ncbi.nlm.nih.gov/nuccore/254160123

While _breseq_ could get the sequence length from the `source` annotation, having the incorrect header line can cause other problems – like incorrectly assigning whether the sequence is linear or circular (which is information only provided in that line to my knowledge). 

**But it's true that GenBank format is a bit squishy, and we'd like to be accommodating to as many input reference file types for compatibility as possible.** So, I think we can propose to fall back on defining sequence length from the `source` annotation if the LOCUS line doesn't work (and vice versa) and displaying a warning if things don't agree or are missing to make things as forgiving as possible.

The VERSION/ACCESSION/LOCUS issue for the `seq_id` has been discussed before. I favor using the VERSION as the `seq_id` because that is supposed to be tied to the exact sequence file, whereas files with the same LOCUS and ACCESSION could have different sequences which would lead to confusion if you generate a GenomeDiff file with one version of the file and then try to analyze or apply it to a later version. I can certainly make the LOCUS line a fallback option if the others are empty though! I also promised a long time ago to add a command line option to allow one to default to using the other possibilities (ACCESSION/LOCUS) as the `seq_id` if that made more sense to you.

I'll try to work on these updates and add some tests to be sure we maintain compatibility going forward

**There isn't any problem that I am aware of with parsing concatenated GenBank files.**

**Comment by jeffreybarrick** [comment]
I implemented this fallback procedure in efa730e3ae94ac06eff7fe1e181b77adb51b0cc4. It should be able to load a GenBank file with this header format. 

Let me know if you want me to roll a temporary binary/source download for you to see if it addresses your issue (please specify which version you download). Otherwise, this will be in the next update that will come after I work through a few other items.

**Comment by jeffreybarrick** [comment]
Fix is available in this version: 
https://github.com/barricklab/breseq/releases/tag/v0.35.3rc1
