### ISSUE TITLE
Transposon annotations to enable breseq to detect mutations

### ISSUE THREAD

**Issue by ramiroricardo** [barricklab/breseq#243]
I have an assembly that was annotated with prokka. Prokka detects IS elements, but I don't think it properly annotates these for breseq to identify new insertions.

Here is part of the GFF file :

```
chromosome	.	CDS	386	1279	.	-	0	Alias=TD_00001;ID=TD_00001;Name=TD_00001;Note=IS3 family transposase ISElsp1;transl_table=11
chromosome	.	CDS	1312	1674	.	-	0	Alias=TD_00002;ID=TD_00002;Name=TD_00002;Note=hypothetical protein;transl_table=11
``` 

Following the breseq docs and #128 I think that for breseq to detect an IS insertion, I would have to change the IS annotation to

```
chromosome	.	repeat_region	386	1279	.	-	0	Alias=TD_00001;ID=TD_00001;Name=IS3;Note=IS3 family transposase ISElsp1;transl_table=11
``` 

Is this correct? or can I keep the original `Name=` field?

Thanks

**Comment by jeffreybarrick** [comment]
You're right that you need to have a feature of type `repeat_region`.

Unfortunately, it's not as easy as swapping a `CDS` to a `repeat_region`... _breseq_ needs the `repeat_region` to correspond to the entire chunk of DNA that is moved during transposition, which is larger than the transposase CDS that is annotated by Prokka. (It needs to know this because that's where the split-mapped reads will start to align when there is a new IS insertion.) 

You may be able to figure out how large the IS actually is by BLASTing the surrounding area against your assembly. (If it is a multicopy IS.) Another resource that can help with annotating the extents of IS elements is [ISFinder](https://isfinder.biotoul.fr/). Generally, this process takes a bit of work and possibly iteration => if you get close and then find that all the predictions by _breseq_ are a bit off (always adding or deleting bases at the ends of the new IS insertions) then you can adjust your annotation.
