### ISSUE TITLE
Annotated reference genome needed?

### ISSUE THREAD

**Issue by termithorbor** [barricklab/breseq#265]
Hi,

is for the analysis an annotated reference genome needed? 
Or can it detect all kinds of mutations without annotation?
If no annotation is needed, how does breseq know which genes are affected?

Thank in advance :)

**Comment by jeffreybarrick** [comment]
I think you partially answered your own question?

If you give _breseq_ an annotated genome it will use this information to describe the effects of mutations on genes. Having IS elements annotated will let it combine JC predictions to fully predict IS insertions, including target site duplications. That's the only case where it may improve the predictions to have annotations. Without this information it will still provide you with evidence of an IS element insertion in the "unassigned JC" section of the output.

If you give _breseq_ an unannotated genome (a FASTA file, for example) then it will still predict mutations, but it will just give their genome coordinates and not be able to report on how they affect genes.

If you need to annotate genes in your sequence, you can use a variety of tools to do this, such as Prokka or RAST. Annotating IS elements, esp. getting the right endpoints for them, is trickier. You can often bootstrap from the JC predictions of _breseq_, plus information on where transposase genes are located, to add these annotations to your genome manually.

**Comment by termithorbor** [comment]
Thanks for the answer.

So the ISfinder database which prokka is using is not good enough for the IS element annotation? Do you probably have a more detailed instruction on how to do it then?

Thanks in advance :)

**Comment by jeffreybarrick** [comment]
Unfortunately, we don't have a nice automated way of doing this, so it's not an easy answer. How hard it is to get there will depend on whether the active IS elements have been characterized in a closely related bacterial species/strain. 

If they have, then you might be able to find the IS sequences in the literature or in a similar genome on NCBI and BLAST those sequences to annotate your genome. Then, you can run _breseq_ using this draft annotation. Often, the endpoints of the IS elements will be a little off...even in the NCBI annotations. You can see this if _breseq_ consistently predicts IS element insertions that have +NNN or ΔX meaning extra nucleotides relative to that end of the IS element are added or deleted. Use this information to move the endpoints of your IS annotations to match.

If you don't have any starting point for identifying the IS element sequences, you can start from _breseq_ output using a reference that does not have them annotated. In this case, you will need to look at the **unassigned junction** section of the results. You will notice junctions that have one orange row (meaning it matches there, but also matches other locations in the genome) and one normal row (meaning it only at that one location). The orange rows are candidates for the edges of IS elements, since they are usually multicopy in the genome. You can look at those locations in the genome and get to a first draft of where the active IS elements are this way. You will then need to re-run and adjust the ends of the IS elements after you do the first draft of annotation this way (as above). in addition, there is sometimes ambiguity about there the junction midpoint is (it could be assigned to either side). Having the IS elements annotated lets _breseq_ properly assign the right amount to the IS element side, and this can only kick in after you have them annotated.

**Comment by dannagifford** [comment]
Just to add, I did as Jeff has suggested with E. coli K-12 BW25113 compared
against E. coli K-12 MG1655. The latter has better IS annotation. IIRC, I
just used BLAST to identify which IS it was, and its rough positioning.

It was worth doing as it vastly improved the ability to identify IS
insertions (which E. coli does a lot of), i.e. bringing them out of the
unassigned JC part of the table. It helped even in cases where I didn't get
the end points exactly right. In that case, it will indicate the IS
movement plus an additional small indel, which is likely spurious.

Modifying the annotation is likely to be useful if you have many sequences
to analyse, otherwise manually identifying what the unassigned JC mutations
are might take less time if it's just a one-off.
