### ISSUE TITLE
Average coverage 

### ISSUE THREAD

**Issue by akfourth** [barricklab/breseq#266]
I'm using breseq v0.35.5. I am using BAM2COV to get the coverage for specific regions of the genome. I see in the tutorial that in the png output file, there should be a line indicating the average coverage over the genome, but I don't see that in my output png file - is that feature not available in the 0.35.5 version ?
Also, I would like to get the average coverage in the table output too (so that I get the exact value) - is this possible ? 
And along the same lines, is it possible to get the average coverage across a specified region ? I know I can calculate it from the BAM2COV output, but I was wondering whether that was a feature that would be useful to add ? In my case, I know the boundaries of an amplification, and so would like to just find the average coverage for the amplified region.
Thanks!

**Comment by jeffreybarrick** [comment]
Add the `-a` option, and then it should add the average genome coverage line to your plots if you are running from a directory of _breseq_ results. (It should have the `output` and `data` folders inside of it.)

You can see this "advanced" option and a few others by running:
```
breseq bam2cov -h
```

We could add those two types of output to be generated as part of the table output (genome average and selected region average). Maybe they should be in special comment lines at the top since they don't fit with the rest of the table? Would that work for you?

**Comment by akfourth** [comment]
Thanks - I'll check out the advanced options for bam2cov.
Sure - the genome average and selected region average can be in comment lines at the top - that would work perfectly - thank you!

**Comment by jeffreybarrick** [comment]
I added the averages as comments to the table file generated by `breseq bam2cov` in the most recent commit (ace490f13a2a3c396ebc221d7e126426a3416115) so it will be in the next release version. The averages are at the **_bottom_** of the file instead of the top for technical reasons.

**Comment by akfourth** [comment]
Thank you so much!
