### ISSUE TITLE
error with gdtools APPLY command

### ISSUE THREAD

**Issue by Julie-bio** [barricklab/breseq#268]
Hi, 

for some samples I have the following error : 
>>> Error(s) in GenomeDiff format. FILE: outputs/32L1_output.gd <<<

>>ERROR: Mutation requires 'before' or 'within' field to disambiguate when and how it occurs because it overlaps bases that are duplicated or deleted by mutation  with id 3909.
>>ON LINE:  3921
SUB<tab>3908<tab>10385,10564<tab>AE014075<tab>4700679<tab>106<tab>CTTGCGAAGCAGACTGACAC

>>ERROR: Mutation requires 'before' or 'within' field to disambiguate when and how it occurs because it overlaps bases that are duplicated or deleted by mutation  with id 3908.
>>ON LINE:  3922
SUB<tab>3909<tab>10565<tab>AE014075<tab>4700679<tab>106<tab>CTTGCGAAGCAGACTGATAC

Is there a was to correct for that ? 

Thanks,

Julie

**Comment by jeffreybarrick** [comment]
This is during a normal _breseq_ run? Which version of _breseq_ are you using? We fixed an error similar to this a while back.

**Comment by Julie-bio** [comment]
Thank you for your reply.
Yes I used breseq to obtain the .gd and then the "gdtools APPLY" command.
I used the version 0.35.1 of breseq.

**Comment by Julie-bio** [comment]
I just tried with the last version (0.35.7) and got the same error.

Thank you in advance for your help,

Julie

**Comment by jeffreybarrick** [comment]
OK. Thanks for trying the new version.

Are you able to share the input files you used in your _breseq_ run so that I can track down where this duplicate is coming from? If you email me at the address in the _breseq_ header I can share a folder for uploading the input files.

**Comment by Julie-bio** [comment]
Ok thank you! I will do that.

**Comment by jeffreybarrick** [comment]
I'm not getting these problem lines in the `output.gd ` file generated by either the current version of _breseq_ or v0.35.1. Was the GD file you are working with generated using an even earlier version of _breseq_? Or was it the result of doing some other `gdtools` commands first?

If that's the case and you still want to use it (without needing to re-run _breseq_), you can edit it with a text editor and delete one of the two offending lines. Since they are duplicates, it shouldn't affect anything.

**Comment by Julie-bio** [comment]
Yes exactly the GD file was generated with an older version.
I will delete those lines.
Thank you very much for your help!
Julie

**Comment by anoukwillemsen** [comment]
I have the same issue with breseq v.0.37.0. When I run the APPLY command using gdtools I get this error:

>>> Error(s) in GenomeDiff format. FILE: output.gd <<<

>>ERROR: Mutation requires 'before' or 'within' field to disambiguate when and how it occurs because it overlaps bases that are duplicated or deleted by mutation  with id 108.
>>ON LINE:   120
SUB<tab>107<tab>220,306<tab>stock_NeTu<tab>1325337<tab>100<tab>TTTTTTTATTACTAATAAAG<tab>frequency=1

>>ERROR: Mutation requires 'before' or 'within' field to disambiguate when and how it occurs because it overlaps bases that are duplicated or deleted by mutation  with id 107.
>>ON LINE:   121
SUB<tab>108<tab>305<tab>stock_NeTu<tab>1325337<tab>100<tab>TTTTTTTATTACTAATAAAGTGGGATAAATTTTTTTTATTACTAATAAAG<tab>frequency=1

When I remove these conflicting lines from the output.gd file, the error does not occur anymore.

**Comment by jeffreybarrick** [comment]
Hi @anoukwillemsen

It looks like you might have a mixture of different repeats of TTTTTTTATTACTAATAAAG in your sample at this location and _breseq_ is having trouble determining their copy number. It cannot estimate their frequencies because you have two variants that are both well-represented and different from the reference at this location. _breseq_ can only deal with predicting frequencies for one variant at a time versus the reference, so it mistakenly assigns both of them a frequency of 100%. (Apparently the reference is not represented at all?)

My strategy for improving the reference sequence to deal with this would be to keep the first that is adding a single unit of the repeat, delete the 2nd one with the longer repeat from the GD file, do APPLY, and then re-run the data to see if it still reports a mutation at this location (which would now be adding a second copy of the repeat. In this case, it should be able to judge what % of the sample is of each of the two types and you can arrive at the consensus in your new reference, hopefully.

**Comment by anoukwillemsen** [comment]
Thank you for you quick answer @jeffreybarrick  
This is very helpful.
