### ISSUE TITLE
gdtools annotate dropping unassigned MC and JC evidence

### ISSUE THREAD

**Issue by sirmicrobe** [barricklab/breseq#279]
After running breseq on lots of populations, I typically subtract my reference mutations using gdtools SUBTRACT then ANNOTATE the output from SUBTRACT and generate a tsv that I then take into R and do allele frequency plotting on all my samples. I've noticed that gdtools ANNOTATE does not include the unassigned MC and new junction evidence that is present in the .gd file and html outputs. The problem is some very important mutations are in these categories that then go missing from large scale analysis. Do you have any recommendations for including these in downstream files? Or maybe I am not following the correct sequence of commands. Thanks for the awesome tool!

**Comment by dannagifford** [comment]
For junction candidates, you can end up with a lot of these, especially
with E. coli, if your reference annotation is missing annotations for
insertion sequences. Adding these to your annotation file can help.

Otherwise you can assess the MC candidates (e.g. by looking at the read
mapping) and add these manually to your output.gd file for each strain.
Then they will be seen by ANNOTATE. This is what I do, and admittedly it's
quite labour intensive when you start working with hundreds of strains. You
could write a script to convert them if you check enough of them and find
them reliable?

Would be interested to know if anyone has a better way...

Danna

**Comment by jeffreybarrick** [comment]
Thanks for sharing the info about your workflows!

The `gdtools` commands were originally meant to only operate on the mutation predictions (3-letter codes), since these are "fully resolved" in that one knows exactly what the sequence change is to the genome. So, we would convert any MC, JC evidence items to MOB, DEL, etc., mutation items by manually editing our GD files before using these commands. I agree this can be very labor intensive when one gets to more than a few strains.

We also been in a situation where we wanted to compare JC predictions across different samples, so this led to adding the `--preserve-evidence` option to `gdtools COMPARE` so it keeps all of the evidence items (2-letter codes).  

There isn't yet a similar `--preserve-evidence` option for `gdtools SUBTRACT`. I can add one, but it brings up at least one question about exactly how you'd expect it to operate on the evidence entries. For RA and JC evidence items, there probably won't be a problem subtracting them. (Although some equivalent JC can be described by different sequence locations, they should all be predicted uniformly by _breseq_). For MC evidence, the size of the prediction can vary from sample to sample, and there is a "fuzzy" end if it extends into a region that only has reads mapping there that also map to other locations. Maybe it could only remove MC items that are completely contained within the fuzzy region described by the one that is being subtracted? Would something like this work for what you want to accomplish?

**Comment by sirmicrobe** [comment]
Thanks for the thoughtful response. I do agree with the 'fuzzy' ends of the MC (and frequency reporting) make it challenging to subtract. To be clear, from what I see MC items are preserved following gdtools SUBTRACT, my problem is that when I export the annotations into a .tsv from a SUBTRACT-ed .gd file using ANNOTATE, those MC items disappear. Just preserving them through ANNOTATE and dumping at the bottom of the final tsv would be nice. Happy to provide the output.gd files after each step and final tsv with an important MC mutation that gets dropped if that would be helpful. Thanks again!

**Comment by jeffreybarrick** [comment]
Oh!

If you aren't using the `--preserve-evidence` or `-e` option with your `gdtools ANNOTATE` command, try that. Currently there is a bug that prevents it from properly preserving `JC` lines. It is possible that also applies to `MC` lines and explains what you are seeing. That is fixed in v0.36.0 that I will push shortly.

**Comment by sirmicrobe** [comment]
Great! Thank you so much!
