### ISSUE TITLE
No marginal prediction, no alignment evidence

### ISSUE THREAD

**Issue by nhuanmc** [barricklab/breseq#280]
Hello,

I run breseq no filter for mixed populations. However, there is no alignment evidence linked to index.html. I am not sure whether I did something wrong.

**Comment by jeffreybarrick** [comment]
Did the run finish without an error message? Do you see HTML files with names beginning in RA in the directory `output/evidence`? How many files do you see in that directory? Since you are asking _breseq_ to output potentially many different alignments, it is possible that it ran out of disk space (or time) during the HTML generation step. This is consistent with having the `index.html` but no files when you click on an RA link. Check on this and let me know what you find.

**Comment by nhuanmc** [comment]
The run was interrupted multiple times because of being out of memory.  output/evidence only have 3 files: annotated.gd, breseq_small.png, and evidence.gd.

**Comment by jeffreybarrick** [comment]
Ok. So you will need to fix this memory limitation to get the full HTML output. It sounds like you are looking for information across the entire genome, which may not be a strength of _breseq_ relative to other approaches such as mapping the reads yourself and using `samtools`. Even if you don't use breseq for analyzing the reads, you could still use the `breseq bam2aln` command to generate HTML figures of alignments from your own BAM files. Also, you could visualize the data from the current _breseq_ run in IGV to see how the reads are aligned. The only thing this won't do is let you look at how reads mapped to new junctions (JC) evidence.

**Comment by nhuanmc** [comment]
Thank you so much.

**Comment by galtoledano** [comment]
Hey, 
I'm having the same problem myself. There is enough memory and breseq finish to run successfully, but still, in the output/evidence I got 3 files: annotated.gd, breseq_small.png and evidence.gd.
Do you have any idea why is that happening?
Thanks, Gal

**Comment by galtoledano** [comment]
Hey @jeffreybarrick, 
I'm having the same problem myself. There is enough memory and breseq finish to run successfully., but still in the output/evidence I got 3 files: annotated.gd  breseq_small.png  evidence.gd

Do you have any idea why is that happening?
Thanks
