### ISSUE TITLE
Suggestion to change error handling when genbank file is improperly formatted 

### ISSUE THREAD

**Issue by danieldeatherage** [barricklab/breseq#281]
If reported sequence length on genbank locus line disagrees with "source" feature, breseq uses source feature length (below). Obviously best solution is to work with correctly formatted reference files, but barring that, i think better to check actual length of sequence in file, and use that length, or crash complaining of discrepancy.

Reference file for the following is 4501 bp in agreement with the locus line, not the source feature.
```
----------------------------------> WARNING <-----------------------------------
Length assigned to sequence 'pBTK1010' from LOCUS line (4501) does not match length from source feature (2484). Length of source feature will be used.
--------------------------------------------------------------------------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error in reference file. Feature of type [misc_feature] named [] on sequence [pBTK1010] has coordinates (2485-2526) that are both outside of the circular sequence bounds (1-2484).
FILE: reference_sequence.cpp   LINE: 1799
```

**Comment by jeffreybarrick** [comment]
Sure, that makes sense to use the actual sequence length and just give a warning when it does not match the LOCUS line and source features (and correct them if we are writing things back out).

Note to self: this will require moving the "circularization" step for features that cross the origin to the generic validation step after all sequence files are loaded rather than doing it now with `SafeCreateFeatureLocations` as each feature is first created.

**Comment by jeffreybarrick** [comment]
It turns out it would be very difficult to delay these checks until after the sequence is loaded.

As a compromise to work better with files edited in Benchling or other editors that may mess up the source annotation that is present in NCBI Genbank files, but set the LOCUS line to the correct length, I set it to prefer the LOCUS line instead when they disagree. That fixes this example and should be more compatible.

This change is present in 5e2d7f3b8bf29b8ed8b7fe926caab2c6710b296e
