### ISSUE TITLE
Compare Breseq analysis from closed reference genome and draft control genome

### ISSUE THREAD

**Issue by AshleySchumann** [barricklab/breseq#285]
Hello,

I am attempting to compare mutations that occur in phage-resistant bacteria samples due to an environmental condition or due to phage infection. To do this I need to perform two breseq analyses on each mutant. The first, which I have completed, is a mutational analysis of my phage-resistant mutants against the NCBI reference strain of my bacterium, which should give mutations caused by both phage infection and the environment This worked well as the NCBI strain is a closed genome (Attached photo, left side).

The second comparison I want to do looks at the effects of just phage infection on mutations within their respective environment. The reference strains for these comparisons were grown for 18 hours in each respective environment without the presence of phage. Then DNA was sequenced. I have assembled these two draft genomes using SPADES and MEDUSA, after which I put the genomes through RAST for annotation.

However, when I breseq my mutants using one of my assembled draft genomes as the reference, all of the mutations output as scaffold positions rather than relative positions (attached photo, right side, same mutant). This makes it difficult to compare the mutations that occur relative to the NCBI reference strain and ones that occur relative to the no phage control. Is this just the common output of how draft genomes will always annotate mutations in breseq? Or is there a technical problem of how I assembled my draft genome that I am missing which is causing the draft genome to show mutations within scaffolds rather than a relative position to the entire genome?

Theoretically, the lab strain should look nearly identical to the NCBI annotation as it is the same strain and have the same gene locations. Yet in breseq, mutations that occur in both analyses (such as the UTP-glucose-1-phosphate uridylyltransferase seen in both near the top) show up at completely different positions in the second analysis. Is this just a remnant of how breseq performs mutational comparisons? Or is my draft genome reference not assembled appropriately enough to look like the ncbi reference?

Any help on this issue would be appreciated. I have attempted assembly of my draft genomes for use as a reference several times and always get to this same result.
<img width="1439" alt="Screen Shot 2021-08-23 at 3 14  PM 1" src="https://user-images.githubusercontent.com/89424411/130526486-a4af0d55-826d-4684-b408-90ff89985623.png">

**Comment by jeffreybarrick** [comment]
If I understand correctly, it sounds to me like you should try running _breseq_ on all of your samples using the NCBI genome as the reference. Then, you can compare the sets of mutations you see in each treatment and figure out any that are common in the reference strains grown for 18 hrs (which shouldn't be many). Your results shown on the left indicate that you have a great closed genome that is very close to your samples to use for a reference.

De novo assembly is typically only needed when there are many (thousands or more) of mutations or significant differences in gene content in your strain versus a database sequence. The assembly process creates an entirely new set of nucleotide sequences (the scaffolds), which is why the numbering doesn't correspond.

**Comment by AshleySchumann** [comment]
Thank you for the reply! I see. I have run breseq on the samples using the
NCBI genome, which are the results on the left panel of the photo for one
mutant. Just to clarify, you're saying that I only have to use the NCBI as
the reference for everything and that I can categorize the mutations that
are also in common with the breseq output of the no phage samples against
NCBI as being because of the environment? And then mutations that are
different between the no phage and phage-resistant mutant samples would
then be due to the phage infection?

That makes sense.

 I was under the impression that I needed to run breseq twice (NCBI:
samples and my No phage: samples) because of the fact that I have both an
environmental variable and phage vs. no phage.

**Comment by jeffreybarrick** [comment]
Yes, I think that will work if I understand your samples correctly.

You can think of _breseq_ as giving you a list of differences between a sample and the reference genome. You can interpret that list as mutations as happening at different stages of evolution since the bacteria you sequenced diverged from that ancestor.
