### ISSUE TITLE
gdtools PHYLOGENY: dnapars not found, even though phylip is installed

### ISSUE THREAD

**Issue by dannagifford** [barricklab/breseq#289]
Hello! I hope this is not merely an oddity of my system set up, but gdtools is looking for a program called 'dnapars'. On Ubuntu, dnapars seems to be invoked instead by 'phylip dnapars', as provided by the phylip deb package.

The gdtools code line in question is here:
https://github.com/barricklab/breseq/blob/a75099a168a687a8233bff0c0fc953ee858fe510/src/c/breseq/gdtools_cmdline.cpp#L1541

A workaround is to put a bash script file called 'dnapars' (don't forget to chmod +x the file) somewhere in your $PATH with the contents:
```
#!/bin/bash
phylip dnapars $@
```
This effectively passes whatever gdtools is trying to pass to the 'dnapars' program through to the 'phylip dnapars' program (the $@ passes all arguments as an array).

**Comment by jeffreybarrick** [comment]
Oh. Interesting. It does seem like that's due to how `phylip` has been packaged for distribution. They've put all of the normal `phylip` executables under some kind of helper main `phylip` helper script, probably so they don't pollute the namespace of executables as much (there are a lot of them that could clash with other installs).

Your solution is a good one. Thanks for sharing.

I'll go ahead and add `phylip dnapars` as a backup for it to try if `dnapars` is not found. I may also make a command-line option that lets you specify the command to call for `dnapars`.

**Comment by jeffreybarrick** [comment]
Add this a while back. Closing.
