### ISSUE TITLE
Question on Inversion predictions

### ISSUE THREAD

**Issue by vr1087** [barricklab/breseq#293]
I noticed a small inversion (~150 bp; in non-repeat region) in one of our pacbio assemblies that was missed by breseq. Breseq sees the corresponding JC evidence but didn't manage to put the evidence together to make an inversion mutation call. I tested its inversion-calling capability separately by manually inverting an unrelated 150 bp sequence in a non-repeat region. Again, breseq sees the two JC items at 100% but did not make the inversion call. Is breseq able to make INV calls on its own or is some manual intervention required? I wasn't able to find an example of an INV mutation call, in fact.

Using breseq 0.35.7 with the default junction evidence options.

**Comment by jeffreybarrick** [comment]
You're correct: _breseq_ does not currently call inversions on its own. 

It does support manually adding INV mutations to Genome Diff files, and _gdtools_ will properly APPLY and COUNT them.

Mostly it doesn't call inversions b/c these are almost always through large repeat regions that are not spanned by short reads, but in your case it sounds like it would have helped.

Thanks for the feedback.

**Comment by vr1087** [comment]
I see that it is possible to check for user-supplied JC and RA evidence items. Is it possible to extend the code to do a similar thing for mutation calls, i.e. INV calls? 

Where can I find an example of a manually added INV mutation call?

Thanks in advance!

**Comment by jeffreybarrick** [comment]
Is the idea that you want to input the mutation into _breseq_ so it is added to the final GenomeDiff file? 

I'd suggest that you do that with a post-run `gdtools MERGE` and then `gdtools ANNOTATE`. The ``--user-evidence-gd`` input is meant for changing how reads map and allowing evidence that is normally below a cutoff to predict mutations versus changing what is predicted from evidence.

Here's an [example of a GenomeDIff file that contains an INV](https://github.com/barricklab/LTEE-Ecoli/blob/master/LTEE-clone-curated/Ara-2_20000gen_11830.gd). (You can ignore the "after" tag which is there because the order of applying the INV relative to another mutation is important.)

The required items are described in the [GenomeDiff format appendix](https://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/gd_format.html#inv-inversion-mutation).

**Comment by vr1087** [comment]
The idea was for _breseq_ to test for the presence of known mutations - mostly just to get around the inability to call inversions. In the short term, I'll store the unassigned evidences and systematically query them to find any missed calls. Ultimately, I think I'll have to supplement our variant calling workflow with a tool designed for detecting SV from short-read data. 

Thanks for the examples.
