### ISSUE TITLE
Help me understand Unassigned new junction evidences

### ISSUE THREAD

**Issue by BatistaB** [barricklab/breseq#294]
Hello,

I'm having a bit of trouble for correctly interpreting the "Unassigned new junction evidence".

What is the influence of the position of the "equal" sign (=) after or before the position.

In my data there are differences in the positions of the = before or after the number.
![image](https://user-images.githubusercontent.com/91222473/141990588-95c596bf-bf1e-4846-9fa7-cc40fcdfb7cb.png)

In this example: https://github.com/barricklab/breseq/issues/170, I could correctly understand the existing duplication, since the example brought the position : 625889= = 628821. (which would be the same as the last mutation in the image).

Could someone help me understand these difference?
Thanks.

**Comment by jeffreybarrick** [comment]
This may be too late to help you, but here's a graphic I'll be adding to the manual that might help.

In brief, the = sign tells you whether that side of the read continues mapping into the reference toward lower coords (= position) or higher coords (position =) from the junction where the two positions are together.

![jc_side_explanation](https://user-images.githubusercontent.com/6777876/167979329-4292bf0c-90ef-4601-9f1e-d088b3c97cce.png)

**Comment by he-hai** [comment]
Hi, how should I understand the two columns of "reads (cov)"? And what is "cov" here? Many thanks.

**Comment by jeffreybarrick** [comment]
These two numbers for a junction are the number of reads crossing each of the two reference positions joined by the new junction that look "normal". They don't match the new junction. 

You can see they are zero for one of your junctions, which is why it comes out at an overall predicted frequency of 100%.

For the others, some reads mapping across this position in the reference map to the new junction (jump to new coordinates) and some map normally.

Cov is the relative coverage, this number of reads divided by the average coverage of the entire genome. So 1.0 would mean that it has as many reads as a normal position in the genome.

**Comment by he-hai** [comment]
Thanks. So the first column is for reads matched to reference, and the second column for chimeric reads matched to new junction.
