### ISSUE TITLE
feature request: long-read sequencing input

### ISSUE THREAD

**Issue by wmoebius** [barricklab/breseq#296]
As far as I understand, breseq is not appropriate for long-read sequencing data (https://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/ASM_Microbe_2021_slides_Barrick.pdf).

With nanopore sequencing being readily available and more easily accessible, I miss this functionality in breseq.

I appreciate that it's probably a lot of work, but wanted to put the feature request out there.

Thanks!

**Comment by jeffreybarrick** [comment]
Thanks for the feedback! 

Long-read sequencing data has very different error properties and maps much differently to genomes compared to short-read data. So, it breaks some of the assumptions/models used by _breseq_. Right now, I'd suggest taking an approach in which you de novo assemble this data (plus Illumina data if available) and then find a tool for predicting mutations from comparing assemblies. (Maybe someone monitoring this thread can suggest a set of tools for this.)

We are starting to generate some nanopore genome re-sequencing data ourselves, and we'll be sure to share any code we come up with that helps make this simpler and generates GenomeDiff or HTML output like that from _breseq_.

**Comment by he-hai** [comment]
I was using ngmlr (https://github.com/philres/ngmlr) + sniffles (https://github.com/fritzsedlazeck/Sniffles)  from https://www.nature.com/articles/s41592-018-0001-7 They are developed from eukaryotes and the output is so hard to read as compared to breseq

**Comment by jeffreybarrick** [comment]
We have a release candidate for v0.38.0 that does this now. We've been using it on some data and the mutation calls seem quite good with >30x coverage data, similar to Illumina for sequencing clones.

In this version of _breseq_ and moving forward, it will automatically detect long reads and split them into smaller read segments for analysis. Of course, this throws out some information you might get about structural variation if you did _de novo_ assembly, but it lets _breseq_ treat the data as it expects according to its reference-based mapping strategy. 

If it is MinION nanopore long-read data then use the `--nanopore` flag and it will ignore mutation predictions in homopolymer repeats of four or more bases that have very high error rates in current nanopore datasets. If you don't do this, you will likely see many spurious predictions of this sort. We still sometimes see problems with indels in the 2-20 bp range not always being called accurately due to alignment issues, but mostly it works.
