### ISSUE TITLE
Error: Repeat feature must have only one location

### ISSUE THREAD

**Issue by tamarahalter** [barricklab/breseq#298]
Hey! 

I get an error when running breseq with one of my gbk files:

+++   NOW PROCESSING Read and reference sequence file input
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Repeat feature must have only one location: 
Please rename the duplicates so that they have unique locus_tags & names, e.g., gene_1 and gene_2
FILE: reference_sequence.cpp   LINE: 699
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
breseq() [0x438ce6]
breseq() [0x5b8603]
breseq() [0x5cfc10]
breseq() [0x425df8]
breseq() [0x40a791]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x2b5cbbca0555]
breseq() [0x417e37]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Unfortunately, it does not say at which line of my gbk file the error occurs. 
I manually checked all locus_tags and names and none of them is assigned to a feature other than the ones supposed to have them (CDS, gene, sig_peptide, ...). However, when I remove all features: mobile_elements and repeat_regions and nc_RNA, the program works fine. So it has to do with some of these features but I could not figure out what causes the issue.

**Comment by jeffreybarrick** [comment]
Can you share the reference sequence file with me? You can send it by email to the address in the breseq header.

**Comment by jeffreybarrick** [comment]
This is "fixed" in the current version of _breseq_. It makes this only a warning, so the run will continue. It also outputs information about the offending features.

The problem features here had complex locations like this:
```
     mobile_element  complement(join(35399..35568,37535..38198))
```
This is fine in genes and other types of features, but _breseq_ does not like it in `mobile_element` or `repeat_region` features because of how it uses these to predict transposon insertions.

My recommendation would be to simplify these features to just one start and end location.

Arguably, _breseq_ could do this on its own, but for not they will be ignored.
