### ISSUE TITLE
Meaning of ‡ symbol in breseq annotation output 

### ISSUE THREAD

**Issue by Burmeistera** [barricklab/breseq#310]
Hello,

I am analyzing output from _breseq_ (v0.35.5) run in polymorphism mode. Two annotations contain the ‡ symbol, and I am searching for the meaning of this ‡ symbol.

The ‡ symbols appear in output--> summary.html --> mutation predictions tab --> annotation column. The two mutations occur in the same gene and same codon. The annotation column contains:
L4F (TTA→TTT) ‡
L4V (TTA→GTA) ‡

Any help appreciated. Thanks!

**Comment by jeffreybarrick** [comment]
This is warning you that you have two (or more than two) base substitutions in the same codon, so the displayed amino acid change may not be correct.

The updated docs mention this a bit in the context of **consensus mode** prediction (in which _breseq_ will predict the new amino acid by combining the changes, for example, if the first and third base were both mutated):
https://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/output.html#single-base-substitution-snp

But, in your case, it looks like you are in **polymorphism mode**, so it is not combining these two individual base substitutions and predicting a new codon of GTT (because it isn't sure they are in the same reads/cells). Instead, you get the double-dagger as a warning that the amino acid change shown may not be the full story.

**Comment by Burmeistera** [comment]
Thanks! This is very helpful and solves my problem.

I went in and took a closer look at the individual reads in the alignment to get the fully story. Interestingly, there are actually four codon variants: the wild type (TTA) plus three mutant genotypes (single change TTT, single change GTA, and the double change GTT).
