### ISSUE TITLE
breseq for nanopore reads

### ISSUE THREAD

**Issue by kesava31** [barricklab/breseq#317]
Hi Barrick
I am using breseq version breseq-0.37.0-Linux-x86_64 to analyse mutations in evolved bacterial genome. Input files are reference gbk file and fastq reads from MinION. But it is taking long time to complete the 02_reference_alignment step.  Can you help me to solve this issue.
Thanks

**Comment by jeffreybarrick** [comment]
_breseq_ is not the right tool for analyzing long-read sequencing data to call variants. It should probably warn you about this when you input very long reads in your FASTQ!!

If you want to shoehorn the data into _breseq_ you have two options: 
1) Chop your FASTQ reads up into ~200-300 base chunks so that it looks like short-read resequencing data.
2) Generate SAM files using another alignment program (possibly minimap2) and then input them into _breseq_ using the `--aligned-sam` option.

The first option is not using some advantages of the long-read data... essentially converting it to Illumina-like data. The second option won't be able to identify IS element insertions or other mutations supported by split read mappings. (I haven't personally tried either option, so I don't know what is best or useful.)

You may be better off de novo assembling the long reads from a sample (using Tricycler, for example) and then calling variants using a tool that can compare assemblies to assemblies or assemblies to a reference. This would be especially true if you want to characterize structural variation.

It looks like this is one possibility for a way of achieving this:
https://github.com/lh3/minimap2/blob/master/misc/README.md

**Comment by jeffreybarrick** [comment]
This feature has been added in the current v0.38.0 release candidate.

See #296 for important info.
