### ISSUE TITLE
rejected polymorphism call predicted as 100% frequency consensus call

### ISSUE THREAD

**Issue by rohanmaddamsetti** [barricklab/breseq#320]
Hi Jeff,

I think I stumbled across a bug in breseq. I'm playing with the RA and polymorphism call parameters, so maybe this happens with the particular parameters I am using. In any case, the prediction looks wildly inconsistent with the RA evidence.

Github won't allow me to attach the HTML file, so here's a screenshot:
<img width="1294" alt="Screen Shot 2022-08-25 at 9 30 54 AM" src="https://user-images.githubusercontent.com/6401836/186678454-33c26e95-92e4-49f6-b4e6-d52f0b659554.png">

**Comment by jeffreybarrick** [comment]
Hi Rohan, 

The T's at the ends of the alignment are being ignored in the frequency calculation (that's why they are lowercase). _breseq_ does this "trimming" to avoid miscalling mutations involving indels at the ends of reads. It is odd that such a high proportion of your reads would happen to end on that base. if this is the whole alignment pictured, the coverage is very uneven, so it is likely something else is also going on here.

**Comment by jeffreybarrick** [comment]
@danieldeatherage Points out that you are referring to why this gets called as a consensus mutation.

There does appear to be a problem with the logic or order of operations of the filters!

The logic _breseq_ is going through would look like this...

1) It correctly gets rejected as a POLYMORPHISM call b/c of the extreme strand bias (no reads on one strand supporting the variant). This converts it to a CONSENSUS call.

2) Then, it _should_ (but doesn't seem to) be subject to the normal filters on CONSENSUS calls, one of which is that it must have a frequency of >80% with the default settings. It doesn't, and therefore should also be rejected as a CONSENSUS call.

I'll look into it when I get a chance.

**Comment by jeffreybarrick** [comment]
Yes, this was a bug! 

The "must be ≥80% frequency to be a consensus call" guard was not on due to in correct initialization of that setting. My fix now makes it so what it says here is correct...

```
  --consensus-frequency-cutoff <arg>                                            
                                   Only predict consensus mutations when the
                                   variant allele frequency is above this value.
                                   (DEFAULT = consensus mode, 0.8; polymorphism
                                   mode, 0.8)
```

 With the current version, you should be able to get the desired behavior by adding this to your command line:
` --consensus-frequency-cutoff 0.8`

**Comment by rohanmaddamsetti** [comment]
Thanks, Jeff!
