### ISSUE TITLE
Unassigned new junction evidence with NA reads

### ISSUE THREAD

**Issue by Dahlai** [barricklab/breseq#328]
Hi,
I am using Breseq to align my sequencing data to a reference genome.

I noticed that some of my unassigned new junction evidence entries have start or end points with "NA" associated "reads (cov)" are highlighted in orange.

![image](https://user-images.githubusercontent.com/20089616/197177467-ccaa02d8-e1d5-487b-a33e-7bd8d08af652.png)

Could you tell me what this exactly means? I can't seem to find an explanation in the docs.

Thank you.

Best,
Michael

**Comment by jeffreybarrick** [comment]
The orange rows (half-rows) in this chart are places where reads are multiply mapping exactly the same to this location and to one or more other locations in your reference files. The NA (not available / not applicable) means that the coverage for these places can't be estimated due to this multi-mapping so it isn't being used in calculating the frequency of the junction. 

In these cases, the overall frequency of the junction is estimated by comparing the number of reads mapping to the junction to the reads mapping to the original (non-junction) sequence on one side (the white row) versus using both of those junctions. These calculations are described here: https://doi.org/10.3389/fgene.2014.00468

**Comment by Dahlai** [comment]
Thank you, this clarified things.
