### ISSUE TITLE
NA and delta frequncy of mutions using gdtools COUNT (breseq v0.37.1)

### ISSUE THREAD

**Issue by xiaolinchu92** [barricklab/breseq#345]
Hi, I am tracking the evolution trajectory of variation frequencies using the gdtools COUNT (breseq v0.37.1).  Two unexpected types of frequencies occurred in the ouput tsv files.  9 time points were sequenced for the population sample.  

For some JC-based variations, NA frequency occurred in the later stages and their frequency were >10% in early time points.  As mentioned in  #337, "NA frequency occurs when both sides of the new junction map to repeat/redundant regions".  
- Why these NA frequencies only occurred in part of the timepoints instead all stages of the evolution as we used the same reference here?  

Similarly, for some RA-based variations, delta (Δ) frequency occurred in the late stages of the evolution, with early frequencies are either all blank (0%) or fluctuates (0%-20%).  I checked individual breseq output (index.html), variation with Δ frequencies did not show up in the output file.  
- Why these Δ frequencies, instead of blank, occurred in the tsv files and how to explain these frequencies?
- Should these Δ frequency be treated as 0% (which may be the case for the always 0%-frequency variations , but is may not the case for the variations whose frequencies fluctuates around 10% at other time points)?   

Thanks in advance.

**Comment by jeffreybarrick** [comment]
My guess about the NA's is that some of your samples had shorter/longer reads (possibly after trimming) that made it possible or not possible to find those junctions.

Δ frequencies are put in a table when the region containing a mutation in other samples is deleted in that sample. They don't necessarily mean zero. It is possible to have a point mutation and then see the entire region containing the point mutation get deleted later. This would lead to a delta in later samples in place of a high or 100% frequency earlier.

As general advice, mutations at <10% frequency are often due to sequencing and/or mapping errors. Most researchers add additional filtering steps to remove false-positives after running _breseq_ in polymorphism mode. These may look for mutations that have consistent trends and/or rule out predictions that have lower coverage. Unfortunately, picking good cutoffs for these steps is a bit of an art b/c of how much the data can differ depending on your sequencing and your reference genome sequence.

One example of applying these kinds of filters is here: https://doi.org/10.1038/nature24287

**Comment by xiaolinchu92** [comment]
Hi Jeff, Thank you for the quick response and the advice for additional filtering.  

I met a very similar problem when running the same protocol for another population.  Both ? and Δ frequency occurred for one specific variation and this happened for both JC and RA variation.  

- What does ? frequency mean?

**Comment by jeffreybarrick** [comment]
A "?" means that there was such low coverage in that sample at that position that _breseq_ could not confidently call any base. These correspond to UNK intervals in the Genome Diff file. The "?" should only happen for RA items.
