### ISSUE TITLE
Complete genome needed?

### ISSUE THREAD

**Issue by termithorbor** [barricklab/breseq#349]
Hi,

is a complete genome (only one contig) needed for the analysis or can the analysis also be done with a fragmented genome?

Thanks in advance :)

**Comment by jeffreybarrick** [comment]
Yes, _breseq_ can analyze input reference sequences containing multiple fragments, like what you typically have after an incomplete _de novo_ assembly. 

**IMPORTANT**: Use the `--contig-reference|-c` option instead of `-r` for passing an entire file from a _de novo_ assembly in which all contigs should have the same coverage. If you have a plasmid and chromosome, put each in a different file and pass the `-c` option twice, so coverage is only assumed to be the same within each input file.

Because incomplete genome assemblies don't resolve repetitive regions of the genome, just be aware that there will likely be some artifactual mutations called associated with those regions. _breseq_ screens out spurious mutations near the ends of contigs that weren't resolved if you use the `--contig-reference` option. Still, there may be others not at the ends of contigs. It's sometimes possible to recognize and screen those out by running _breseq_ on the reads used to create the assembly or running the data for the ancestor of your experiment against it. How well this works depends on the assembly and repeat structure of the reference genome.

**Comment by termithorbor** [comment]
Thanks for the answer. Just a breif follow-up question: Do you know a good tool for filtering an assembled genome by contig coverage? Because then I would only concider contigs which have a depths of ~1 because they should resemble "true" genome contigs.

**Comment by jeffreybarrick** [comment]
I think you can set an option to filter out contigs with unusual coverage in most assemblers. I'd first look at the options of the program you are using for assembly to do this.

**Comment by termithorbor** [comment]
One final question: Am I right that for using an annotated genome the filtering has to be done before the annotation?
Thanks again.
