### ISSUE TITLE
Hard drive fills entirely after running breseq for some time, until reboot

### ISSUE THREAD

**Issue by Antovigo** [barricklab/breseq#351]
I am running breseq on many files, processed one by one from a bash script. Every time, after about 6-7 populations are processed, my computer stalls and throws "no space left on device" issues. The hard drive is indeed reported as full, but there's nothing to account for it in my home folder. It looks like it produces some temporary files somewhere (but I don't see anything in /tmp).
Strangely, if I reboot the computer, the space is freed and I can continue processing my genomes until it's full again.

I'm running Ubuntu 22.04 on a laptop with >300GB of free space, so it's pretty substantial. The OS and home folders are all on the same partition.

Do you know what could be going on?

**Comment by jeffreybarrick** [comment]
All the files _breseq_ creates are in the output folder. (Nothing in `/tmp`)

Your issue is most likely related to how your hard drive is freeing up space from files that have been deleted, as _breseq_ does create and then destroy a significant number of files during and at the end of each run. To save wear and tear on solid state drives, it's common for the OS to delay how often it cleans up deleted disk space. I'm not a Ubuntu guru, but maybe there is some way to change when or how often it does that.

As a general space saving tip: you may be using more sequencing data than is helpful/needed need if you are analyzing clonal sequencing data and the coverage is >40-60. You can use the `-l 80` option to limit how many reads _breseq_ will use to a nominal reference genome coverage of 80x, which could greatly reduce the amount of hard drive space used if you have much more data than needed. The output from _breseq_ can also gets excessively large if your reference genome is not closely related to the sample genome.
