### ISSUE TITLE
A question about "gdtools COMPARE" html output

### ISSUE THREAD

**Issue by adirot** [barricklab/breseq#354]
Hi!
I searched the documentation but I couldn't find an answer.
In the predicted mutations table I get one of the signs ? , Δ, or 100%. What do each of them mean?
Thank you!

**Comment by jeffreybarrick** [comment]
- '100%' means the mutation is present in that sample. Lower percentages can show if you run _breseq_ in POLYMORPHISM mode. In CONSENSUS mode, it should always be 100%.
- '?' means that _breseq_ was unable to call mutations in that region in that sample due to low coverage (it overlaps a MC evidence item). This situation can occur when you have low coverage for the entire genome in that sample. If you have good coverage, it can also occur in certain regions if you have shorter reads in that sample such that you don't have any or many reads that overlap the mutation AND uniquely map to that one site in the genome versus equally well to others.
- 'Δ' means that the region overlapping this mutation was deleted in that sample. The mutation could have been present before the deletion, but there is no way to know from that one sample, whether this was the case, since the entire region is now gone.

Let me know if you have any follow up questions!

**Comment by adirot** [comment]
Thank you for the answer!
I eventually found it in the "help" of the function, but I think it would be better to put this explanation in the manual too. 
Adi
