### ISSUE TITLE
Is -c the same as -r for single sequence references?

### ISSUE THREAD

**Issue by padpadpadpad** [barricklab/breseq#359]
I have some reference genomes that have several contigs, but that we expect to have the same coverage, and some that only have a single contig.

Is there any difference between running with -c and --contig-reference compared to -r? Especially with a single sequence in a reference?

**Comment by jeffreybarrick** [comment]
Here are the differences:

Using `-c` instead of `-r` for an input reference file does the following: 

1 All of the sequences in that input file will be assumed to have the same average coverage and coverage distribution (this is used to determining cutoffs for calling MC evidence / deletions). You should split out chromosome and plasmid contigs into different files if these exist in your reference.
1 Mutations/evidence won't be called if they fall completely within twice the average read length of the end of one of the input sequences (i.e. are at the edge of what is assumed to be a contig).

Older versions of _breseq_ only did (1) and not (2).

In your case, there may not really be a difference, but those are the things to watch out for!

**Comment by padpadpadpad** [comment]
Thanks for the incredibly quick reply @jeffreybarrick. So from my understanding of (2) then for 150bp reads mutations will only be called after 300bp (and the same at the end of the contig/sequence)?

**Comment by jeffreybarrick** [comment]
Yes, that's correct. 

I _think_ the mutation/evidence has to be completely within the 300 bp at one end to be not shown in this case. If it was larger and overlapped the 300 bp and the "not 300 bp" then it would be shown.

We added this b/c we were tired of seeing a lot of junction predictions connecting contigs in ambiguous ways.
