### ISSUE TITLE
Mutation not matching annotation

### ISSUE THREAD

**Issue by erikwolfsohn** [barricklab/breseq#366]
I'm not sure if this is an error or if I'm just not interpreting my output correctly. I have a C -> T mutation which is supported by the read alignment evidence, but the annotation is G257D G**G**T -> G**A**T. I see there are a couple of isolated reads in there that match the annotation, but the majority do not:

<img width="1247" alt="image" src="https://github.com/barricklab/breseq/assets/17581236/323ba40a-cb70-4103-ad9b-80d441f6d29b">

**Comment by jeffreybarrick** [comment]
Here's how to interpret things:

The mutation and read alignment are with respect to the top genome strand, where there is a C->T change. Because the ompA gene is on the reverse strand, the codon change in the gene is GGT->GAT as shown in the annotation column (the C->T change is G->A on the reverse strand). The arrow by the ompA gene gives the strand of the genome it is on (reverse).

**Comment by erikwolfsohn** [comment]
Got it, thank you! When the predicted mutation is in an intergenic region, does the arrow indicate what strand the next closest gene is on? For example:

<img width="1259" alt="image" src="https://github.com/barricklab/breseq/assets/17581236/ac4d799f-6c61-420c-b07b-0e3a4042459a">

**Comment by jeffreybarrick** [comment]
The mutation is always described on the top strand.

The gene here for an intergenic mutation gives the strand of the two adjacent genes on both sides of the slash.

SD200_17140 is in the forward (top strand) direction. Same for iroB.
