### ISSUE TITLE
samtools included with patch

### ISSUE THREAD

**Issue by alexmyczko** [barricklab/breseq#367]
what is the exact reason and details on this patch?

http://sid.ethz.ch/debian/breseq/2024/breseq-0.38.3/extern/samtools_modifications.txt

asking for this:
https://github.com/barricklab/breseq/issues/181

**Comment by jeffreybarrick** [comment]
It's been a long time since I looked a this...

Conceptually, these changes were made so _breseq_ can build and link to its own private and stable version of samtools that has a modification such that it will return all alignments of a read and not just the first 8000.

So, if this question is related to making a _breseq_ package, one thing to know is that you should not list samtools as a separate prerequisite.
