### ISSUE TITLE
How to compare results from many strains?

### ISSUE THREAD

**Issue by cgliss** [barricklab/breseq#371]
Hello Barrick Lab,

I need to compare the mutations between 100+ strains. Many of these strains have new junction evidence and missing coverage, which doesn't show up with gdtools COMPARE. Is there another way to compare the mutations? 

For gdtools APPLY is there a way to apply the new junction evidence and missing coverage? 

Thank you in advance!

**Comment by jeffreybarrick** [comment]
JC and MC _evidence_ are "unresolved" in the sense that they don't specify an actual _mutation_ that would explain how to precisely edit the genome to update it. So, to answer your 2nd question first, there is no way to APPLY them.

The MC evidence is accounted for somewhat in a COMPARE table b/c any mutations in another sample that overlap it are given a ? in the genome with the MC because there were not enough reads to call that mutation (or it is deleted) so it is indeterminate whether it is present in the sample with MC evidence.

Typically, we manually resolve these to deletions, mobile element insertions, duplications, etc. by hand-curating the output GenomeDiff files (editing them in a text editor). We then check our edits by doing a gdtools APPLY and running the original reads against the updated reference file for that sample. If the edits are correct, the new _breseq_ run should come back "clean" = with no mutations predicted. At this point, you can make a COMPARE table that is not missing anything.

I recognize that's a daunting and sometimes impossible task to do this when there are many samples and when there are very complex rearrangements in a sample relative to the reference genomes. Sometimes it is advisable to "fix" your reference genome by doing this work on one sample and then running your reads against this updated reference.

There have been requests to try to show evidence in the compare table... but I think it would be pretty messy and not so helpful... as each MC and JC even for the same mutation can sometimes have different endpoints that would lead to them not being grouped together in a line as you'd like.

I'm open to suggestions about how to possibly make a way of displaying this information across samples.

**Comment by cgliss** [comment]
Thank you so much for the thorough reply! It does seem tough to represent this well, my suggestion is a table that shows when strains have JC in the same genes, even if it might not necessarily be in the same location. This would definitely speed up the process of comparing the JC across many strains.

**Comment by cgliss** [comment]
Follow-up question: for duplications is that normally indicated by JC evidence? How can you tell based on the JC evidence if it is a duplication? Thanks in advance!
