### ISSUE TITLE
Ways to shorten assembly time when using plasmid reference 

### ISSUE THREAD

**Issue by he-hai** [barricklab/breseq#372]
Hi, I would like to consult a way to shorten assembly time when using additional plasmids reference. Thanks. 

I noticed that when using additional references, such as plasmid, for assembly, the run time is significantly longer. Considering I could allocate more CPUs and/or RAM using computing cluster, is it possible to set it up (and how) so that the run time become short? Thank you.

**Comment by jeffreybarrick** [comment]
Sorry for the slow reply – just noticed this one.

It's odd for adding a plasmid to slow run time much, esp. if it is a small sequence compared to the chromosome(s). My best guess would be that you have very high coverage of the plasmid, perhaps because it is high-copy, and also a dataset with very high coverage overall of the genome.

The simplest "fix" would probably be to limit how much of your dataset you are using with _breseq_. You can do this by adding the ` -l,--limit-fold-coverage` option to your command.

For example, `-l 60` would limit the number of bases in the reads it uses to enough to nominally cover the genome 60x. The actual coverage would be lower, since some of those reads won't map. If you have a plasmid, the plasmid may also unequally draw away some of those reads.

In practical terms, if you are calling mutations in a clonal sample (consensus mode), usually all mutations are reliably identified once you have >40x coverage, so maybe set it a bit higher than this.
