### ISSUE TITLE
Return VERSION (rather than LOCUS) from GenBank file in GenomeDiff seq_id

### ISSUE THREAD

**Issue by lyschoening** [barricklab/breseq#89]
Would it be possible to add a command line option to return the GenBank file's version (including the .123 version suffix) instead of the locus name in the GenomeDiff output as seq_id?

**Comment by jeffreybarrick** [comment]
I can see why you want to do this, but can you sell me on adding this as a _breseq_ option versus the alternative scenario in which the user who wants this kind of seq_id edits the GenBank file to put the VERSION info on the LOCUS line and uses that as input into breseq? 

It wouldn't be too hard to add this kind of option to _breseq_, but then I'd also have to add the option to all of the utility and gdtools commands that require references sequences as input, otherwise the output files generated with this new option would not be compatible with them. Plus, I try to keep the new options added to breseq to a minimum because there are already so many.

**Comment by lyschoening** [comment]
I could of course edit the locus to be the accession number & version, but sequences from NCBI are simply not formatted that way and I don't want to edit reference sequences that are supposed to be authoritative. 


The weaker argument — as nobody seems to stick to the GenBank – is that the standard restricts the locus to 16 characters and doesn't require it to remain unchanged. Some parsers might not appropriately interpret a '.' in the name. LOCUS and VERSION are both mandatory. That requirement is often ignored, of course, but when both are present the version seems more appropriate. It should be the default, but backwards-compatibility would necessitate a flag.

> LOCUS	- A short mnemonic name for the entry, chosen to suggest the
> sequence's definition. Mandatory keyword/exactly one record.
> 
> ACCESSION	- The primary accession number is a unique, unchanging
> identifier assigned to each GenBank sequence record. (Please use this
> identifier when citing information from GenBank.) Mandatory keyword/one
> or more records.
>
> VERSION		- A compound identifier consisting of the primary
> accession number and a numeric version number associated with the
> current version of the sequence data in the record. This is optionally
> followed by an integer identifier (a "GI") assigned to the sequence
> by NCBI. Mandatory keyword/exactly one record.

ftp://ftp.ncbi.nih.gov/genbank/gbrel.txt

**Comment by jeffreybarrick** [comment]
OK. I'll work on adding this as an option for now (only for the main _breseq_ pipeline), and give you access to a patched version for testing once that's ready.

I could see eventually making VERSION the default sequence id in a future major _breseq_ release. It does make more sense to use it, when it's available.

**Comment by wumuyao1996** [comment]
Can I have access to it too?
It's cool to run into similar issues as Lars I feel like i'm following in his footsteps.

**Comment by jeffreybarrick** [comment]
I finally implemented this as the `--use-version-for-seq-id` option in https://github.com/barricklab/breseq/commit/36a9be6d40fb0c18a7f2bc837fe7211204127480!

Let me know if you encounter any problems with it!
