### ISSUE TITLE
Polymorphism mode reject=FREQUENCY_CUTOFF error

### ISSUE THREAD

**Issue by yjiao** [barricklab/breseq#94]
Hello,

I'm seeing a strange behavior in polymorphism mode. Here's a line from the output gd file:
```
RA      693     .       NC_007795       1676165 0       T       G       bias_e_value=2235590    bias_p_value=0.792378   consensus_score=212.3   fisher_strand_p_value=0.432611  frequency=9.28129196e-01        ks_quality_p_value=0.992518     major_cov=37/40 major_frequency=9.28129196e-01  minor_cov=4/2   polymorphism_score=13.7 prediction=polymorphism ref_base=G      reject=FREQUENCY_CUTOFF total_cov=42/42 variant_frequency=9.28129196e-01 
```

Here's an excerpt from the command:
```
my $breseqCmd = "$breseqPath -r $gbkPath -o $outdir/$sampleoutname[$i]/ -j 3 -n $sampleoutname[$i] --polymorphism-prediction --polymorphism-frequency-cutoff 0.2 $trim1 $trim2"; 
```

When I look at this region in IGV, it is very obvious that there is a mutation there. Both major and minor frequency looks to be above the 0.2 cutoff, so I'm not sure why the "reject=FREQUENCY_CUTOFF" is there. Not sure if I'm misunderstanding how polymorphism mode should work, but this seemed strange to me.

**Comment by jeffreybarrick** [comment]
Ok. I think I see what is happening.

There are two frequency cutoffs in play, the "polymorphism" and "consensus" ones.

Normally, these are set to 0.95 and 0.05 by default and this means:
`no mutation < 0.05 < polymorphism predicted < 0.95 < consensus mutation predicted`

With your settings, it creates a blind spot between the polymorphism and consensus predictions:
`no mutation < 0.2 < polymorphism predicted < 0.8 *no mutation!* < 0.95 < consensus mutation`

That's a pretty confusing result due to it not believing polymorphisms predicted < 0.2 or > 0.8 = 1 - 0.2 because they are equally hard to tell apart from 0% or 100% respectively.

I think the best solution is for the default in breseq to be change so that --consensus-frequency-cutoff is set to 1 - polymorphism-frequency-cutoff unless it is specified (perhaps even with a warning if these settings create this blind spot area).

For now, you should be able to get the expected behavior (it will predict the example mutation as a 100% mutation because it is >80%) by setting --consensus-frequency-cutoff to 0.8.

**Comment by yjiao** [comment]
Thanks for the quick response! We'll set the --consensus-frequency-cutoff and hopefully that will fix the issue.
