### ISSUE TITLE
fatal error result code 256

### ISSUE THREAD

**Issue by cfblaeb** [barricklab/breseq#98]
I have sequenced 66 samples.
Running breseq on each sample against the same reference genome.
On 50 samples it works. On 16 samples it fails at the same step.

Heres the output from terminal for 1 of the failing samples

[system] R --vanilla < /opt/breseq-0.28.0-Linux-x86_64/bin/../share/breseq//coverage_distribution.r > sample1/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log distribution_fil
e=sample1/03_candidate_junctions/0.unique_only_coverage_distribution.tab plot_file=sample1/03_candidate_junctions/0.coverage.pdf deletion_propagation_pr_cutoff=2.32333e-05
    POSITION:3370000
Warning message:
In sum(((1:end_i_for_fits) \* X.for.fits)) :
  integer overflow - use sum(as.numeric(.))
Error in nlm(f_nb, c(mean_estimate, try_size), iterlim = 1000, print.level = this.print.level) :
  missing value in parameter
Execution halted
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] R --vanilla < /opt/breseq-0.28.0-Linux-x86_64/bin/../share/breseq//coverage_distribution.r > sample1/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log distribution_fil
e=sample1/03_candidate_junctions/0.unique_only_coverage_distribution.tab plot_file=sample1/03_candidate_junctions/0.coverage.pdf deletion_propagation_pr_cutoff=2.32333e-05
Result code: 256
FILE: libbreseq/common.h   LINE: 1378
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by cfblaeb** [comment]
Tried it with on-machine-compiled version of 0.28.1. Same Error.

**Comment by cfblaeb** [comment]
It appears it works in 0.27.2 (still running but past error point).
I think this heavily suggests the error was introduced in the recent commits for coverage_distribution.r.
Either 6bda0fb or 33d0477

**Comment by jeffreybarrick** [comment]
Thanks for the comments and isolating the change that leads to the problem. The change in coverage.r in 0.28.0 was to address some other shortcomings/speed up processing for some challenging data sets, so this appears to be an unintended side effect of that.

If you could share one of your problem data sets with me, I'd like to see what the characteristics of your data set are that are causing the problem, and fix the new bug (rather than rollback the change). If you contact me by email at the address in the breseq command line output, I can set up a private place for you to copy some example input files to.

**Comment by jeffreybarrick** [comment]
Bug fixed in v0.28.1

**Comment by RachelHick** [comment]
Hello,

I'm running the tutorial on mac and here is the failed message any help would be great.
Error running command:

[system] R --vanilla < /usr/local/bin/../share/breseq//coverage_distribution.r > REL8593M-default/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log distribution_file=REL8593M-default/03_candidate_junctions/0.unique_only_coverage_distribution.tab plot_file=REL8593M-default/03_candidate_junctions/0.coverage.pdf deletion_propagation_pr_cutoff=2.32374e-05
Result code: 256
FILE: ./libbreseq/common.h   LINE: 1479
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
0x000000010cf33bbd _ZN6breseq6SYSTEMESsbbb
0x000000010cfd15bb _ZN6breseq20CoverageDistribution3fitERNS_8SettingsESsSsd
0x000000010cfd20d2 _ZN6breseq20CoverageDistribution36analyze_unique_coverage_distr
0x000000010cfd3013 _ZN6breseq20CoverageDistribution37analyze_unique_coverage_distr
0x000000010cf2b5bf _Z21breseq_default_actioniPPc
0x000000010cf35794 main
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I'm running breseq 0.31.1  revision ab36e33bf539 with ---> bowtie2  :: version 2.3.3.1 [/usr/local/bin/bowtie2]
---> R        :: version 3.4.0 [/usr/local/bin/R]
Maybe I've made an error but any tips would be great!

Thanks in advance, Rachel

**Comment by jeffreybarrick** [comment]
Can you run the command:

`R --vanilla < /usr/local/bin/../share/breseq//coverage_distribution.r > REL8593M-default/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log distribution_file=REL8593M-default/03_candidate_junctions/0.unique_only_coverage_distribution.tab plot_file=REL8593M-default/03_candidate_junctions/0.coverage.pdf deletion_propagation_pr_cutoff=2.32374e-05`

from the same directory that you were running _breseq_ from and post the result (which should give a more detailed error)?

Also, how did you install R? (Download of package from R website or through a package manager like homebrew?)

**Comment by RachelHick** [comment]
Thanks, for your quick response. 

R came install on the IT department from the University. Everything is install in the the usr/local/bin. 

From the function above is there to many/ as should it be R --vanilla < /usr/local/bin/../share/breseq/coverage_distribution.r instead?

**Comment by jeffreybarrick** [comment]
Does the command run as I posted? (I think it will run with or without the double slash.)

**Comment by RachelHick** [comment]
Yes seem so. Would the Unique_only_coverage log help?

**Comment by jeffreybarrick** [comment]
Yes, please send/post the contents of "REL8593M-default/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log "

Does it not print anything to the command line after you run the command in a terminal window?

**Comment by RachelHick** [comment]
No it doesn't print anything in the command line but here the REL8593M-default/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log

ARGUMENT 'distribution_file=REL8593M-default/03_candidate_junctions/0.unique_only_coverage_distribution.tab' __ignored__

ARGUMENT 'plot_file=REL8593M-default/03_candidate_junctions/0.coverage.pdf' __ignored__

ARGUMENT 'deletion_propagation_pr_cutoff=2.32374e-05' __ignored__


R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> ##
> ##
> ## AUTHORS
> ##
> ## Jeffrey E. Barrick <jeffrey.e.barrick@gmail.com>
> ##
> ## LICENSE AND COPYRIGHT
> ##
> ## Copyright (c) 2008-2010 Michigan State University
> ## Copyright (c) 2011-2017 The University of Texas at Austin
> ##
> ## breseq is free software; you can redistribute it and/or modify it under the
> ## terms the GNU General Public License as published by the Free Software
> ## Foundation; either version 1, or (at your option) any later version.
> ##
> ##
> 
> ## Arguments:
> ##   distribution_file=/path/to/input 
> ##   plot_file=/path/to/output 
> ##   deletion_propagation_pr_cutoff=float
> ##   plot_poisson=0 or 1
> ##   pdf_output=0 or 1
> 
> ## Returns these values printed out to output log
> ## 
> ##  1. print(nb_fit_size); # 0 if fit failed
> ##  2. print(nb_fit_mu);   # 0 if fit failed
> ##  3. print(m)q
> ##  4. print(v)
> ##  5. print(D)
> ##  6. print(deletion_propagation_coverage)
> ##     -1 if it was <1 after fitting (implying reference sequence is deleted)
> ##
> 
> par(family="sans")
> 
> plot_poisson = 0;
> pdf_output = 1;
> 
> this.print.level = 0
> #this.print.level = 2
> 
> for (e in commandArgs()) {
+   ta = strsplit(e,"=",fixed=TRUE)
+   if(! is.na(ta[[1]][2])) {
+     temp = ta[[1]][2]
+  #   temp = as.numeric(temp) #Im only inputting numbers so I added this to recognize scientific notation
+     if(substr(ta[[1]][1],nchar(ta[[1]][1]),nchar(ta[[1]][1])) == "I") {
+       temp = as.integer(temp)
+     }
+     if(substr(ta[[1]][1],nchar(ta[[1]][1]),nchar(ta[[1]][1])) == "N") {
+       temp = as.numeric(temp)
+     }
+     assign(ta[[1]][1],temp)
+     cat("assigned ",ta[[1]][1]," the value of |",temp,"|\n")
+   } else {
+     assign(ta[[1]][1],TRUE)
+     cat("assigned ",ta[[1]][1]," the value of TRUE\n")
+   }
+ }
assigned  /Library/Frameworks/R.framework/Resources/bin/exec/R  the value of TRUE
assigned  --vanilla  the value of TRUE
assigned  distribution_file  the value of | REL8593M-default/03_candidate_junctions/0.unique_only_coverage_distribution.tab |
assigned  plot_file  the value of | REL8593M-default/03_candidate_junctions/0.coverage.pdf |
assigned  deletion_propagation_pr_cutoff  the value of | 2.32374e-05 |
> 
> deletion_propagation_pr_cutoff = as.numeric(deletion_propagation_pr_cutoff);
> 
> ## initialize values to be filled in
> nb_fit_mu = 0
> nb_fit_size = 0
> m = 0
> v = 0
> D = 0
> deletion_propagation_coverage = -1
> 
> min_fraction_included_in_nb_fit = 0.01
> 
> #load data
> X<-read.table(distribution_file, header=T)
> 
> #table might be empty
> if (nrow(X) == 0)
+ {
+   #print out statistics
+   
+   print(nb_fit_size);
+   print(nb_fit_mu);
+   
+   print(m)
+   print(v)
+   print(D)
+   
+   print(deletion_propagation_coverage)
+   
+   q()
+ }
> 
> #create the distribution vector and fit
> Y<-rep(X$coverage, X$n)
> m<-mean(Y)
> v<-var(Y)
> D<-v/m
> 
> ###
> ## Smooth the distribution with a moving average window of size 5
> ## so that we can more reliably find it's maximum value
> ###
> 
> ma5 = c(1, 1, 1, 1, 1)/5;
> 
> ## filtering fails if there are too few points
> if (nrow(X) >= 5) {
+   X$ma = filter(X$n, ma5)
+ } else {
+ 	X$ma = X$n
+ }
> 
> i<-0
> max_n <- 0;
> min_i <- max( trunc(m/4), 1 ); #prevents zero for pathological distributions
> max_i <- i;
> for (i in min_i:length(X$ma))
+ {		
+   #cat(i, "\n")
+ 	if (!is.na(X$ma[i]) && (X$ma[i] > max_n))
+ 	{
+ 		max_n = X$ma[i];
+ 		max_i = i;
+ 	}
+ }
> 
> ##
> # Censor data on the right and left of the maximum
> ##
> 
> start_i = max(floor(max_i*0.5), 1);
> end_i = min(ceiling(max_i*1.5), length(X$ma));
> 
> if (start_i == end_i)
+ {
+   print(nb_fit_size);
+   print(nb_fit_mu);
+   
+   print(m)
+   print(v)
+   print(D)
+   
+   print(deletion_propagation_coverage)
+   
+   q()
+ }
> 
> cat("Fitting from coverage of ", start_i, " to ", end_i, ".\n", sep="")
Fitting from coverage of 26 to 80.
> 
> ##
> # Coarse grain so that we are only fitting a number of bins that is 1000-2000
> #
> # The later adjustment for doing the fits this way is to multiply the means
> # of the negative binomial and poisson distributions by the binning number.
> # (The size parameter of the negative binomial doesn't need to be adjusted.)
> ##
> 
> 
> num_per_bin = trunc((end_i - start_i) / 1000)
> 
> if (num_per_bin > 1) 
+ {
+   cat("Coarse-graining for fits\n")
+   start_i_for_fits = trunc(start_i/num_per_bin)
+   end_i_for_fits = ceiling(end_i/num_per_bin)
+   num_bins = end_i - start_i  + 1
+   cat("Fitting from coverage in adjusted bins ", start_i_for_fits, " to ", end_i_for_fits, ".\n", sep="")
+   cat("Number of bins ", num_bins, ". Each bin has ", num_per_bin, " coverage values.\n", sep="")
+ 
+   # Create a new vector where we've added together values in bins
+   X.for.fits = vector("double", end_i_for_fits)
+   for (i in start_i_for_fits:end_i_for_fits)
+   {
+     for (j in 1:num_per_bin)
+     {
+       if (i*num_per_bin+j <= length(X$n))
+       {
+         X.for.fits[i] = X.for.fits[i] + X$n[i*num_per_bin+j]
+       }
+     }
+   }
+ 
+ } else {
+   ## AVOID num_per_bin equalling zero!!
+   X.for.fits = X$n[1:end_i]
+   num_per_bin = 1
+   start_i_for_fits = start_i
+   end_i_for_fits = end_i
+ }
> 
> 
> ##
> # Now perform negative binomial fitting to the censored data
> ##
> 
> inner_total<-0;
> for (i in start_i_for_fits:end_i_for_fits)
+ {
+ 	inner_total = inner_total + X.for.fits[i]; 
+ }
> # Yes: it's correct to use X here because we want the overall total total
> total_total<-sum(X$n);
> 
> ## let's preconstruct these for speed
> dist = vector("double", end_i_for_fits)
> 
> f_nb <- function(par) {
+ 
+ 	mu = par[1];
+ 	size = par[2];
+ 
+   if ((mu <= 0) || (size <= 0))
+   {
+     return(0);
+   }
+   
+   cat(start_i_for_fits, " ", end_i_for_fits, "\n");
+   cat(mu, " ", size, "\n");
+   
+ 	dist<-c()
+ 	total <- 0;
+ 	for (i in start_i_for_fits:end_i_for_fits)
+ 	{	
+ 		dist[i] <- dnbinom(i, size=size, mu=mu);
+ 		total <- total + dist[i] 
+ 	}
+ 	#print (mu, size)
+ 
+  	l <- 0;
+ 	for (i in start_i_for_fits:end_i_for_fits)
+ 	{
+ 		l <- l + ((X.for.fits[i]/inner_total)-(dist[i]/total))^2;
+ 	}
+ 	return(l);
+ }
> 
> 
> 
> ## Fit negative binomial 
> ## - allow fit to fail and set all params to zero/empty if that is the case
> nb_fit = NULL
> ## as.numeric prevents overflow in sums involving integers
> mean_estimate = sum((as.numeric(1:end_i_for_fits)*as.numeric(X.for.fits)))/sum(as.numeric(X.for.fits))
> 
> nb_fit_mu = -1
> nb_fit_size = -1
> try_size = 100000
> try_means_index = 1
> #This is a list of different means to test <-  sometimes the actual mean doesn't lead to a fit
> try_means = c(mean_estimate, 
+               end_i_for_fits, 
+               start_i_for_fits, 
+               1*(end_i_for_fits + start_i_for_fits)/4,
+               2*(end_i_for_fits + start_i_for_fits)/4,
+               3*(end_i_for_fits + start_i_for_fits)/4
+               )
>               
>               
> nb_fit = c()
> 
> while ( ((nb_fit_mu < 0) || (nb_fit_size < 0) || (nb_fit$code != 1)) && (try_size > 0.001) && (try_means_index <= length(try_means)))
+ {
+   try_size = try_size / 10
+   try_mean = try_means[try_means_index]
+ 
+   ## SIZE ESTIMATE from the censored data can be negative, so try various values instead
+   cat("Try Mean: ", try_mean, " Size: ", try_size, "\n")
+ 
+   try( suppressWarnings(nb_fit<-nlm(f_nb, c(try_mean, try_size), iterlim=1000, print.level=this.print.level)) )
+ 
+   nb_fit_mu = nb_fit$estimate[1];
+   nb_fit_size = nb_fit$estimate[2];
+ 
+   cat("Fit Mean: ", nb_fit_mu, " Size: ", nb_fit_size, " Code: ", nb_fit$code, "\n")
+   
+   if (try_size <= 0.001) {
+     try_size = 100000
+     try_means_index = try_means_index + 1
+   }
+ }
Try Mean:  54.00122  Size:  10000 
26   80 
54.00122   10000 
26   80 
54.00122   10000 
26   80 
54.00128   10000 
26   80 
54.00122   10000.01 
26   80 
54.00132   10000 
26   80 
54.00137   10000 
26   80 
54.00132   10000.01 
26   80 
54.3644   10000 
26   80 
54.36445   10000 
26   80 
54.3644   10000.01 
26   80 
54.36702   10000 
26   80 
54.36708   10000 
26   80 
54.36702   10000.01 
26   80 
54.36704   10000 
26   80 
54.3671   10000 
26   80 
54.36704   10000.01 
Fit Mean:  54.36704  Size:  10000  Code:  2 
Try Mean:  54.00122  Size:  1000 
26   80 
54.00122   1000 
26   80 
54.00122   1000 
26   80 
54.00128   1000 
26   80 
54.00122   1000.001 
26   80 
54.00133   1000 
26   80 
54.00138   1000 
26   80 
54.00133   1000.001 
26   80 
54.40167   999.9956 
26   80 
54.40173   999.9956 
26   80 
54.40167   999.9966 
26   80 
54.40488   999.9934 
26   80 
54.40494   999.9934 
26   80 
54.40488   999.9944 
26   80 
54.40644   999.9891 
26   80 
54.40649   999.9891 
26   80 
54.40644   999.9901 
26   80 
54.41109   999.9633 
26   80 
54.41114   999.9633 
26   80 
54.41109   999.9643 
26   80 
54.4173   999.8987 
26   80 
54.41735   999.8987 
26   80 
54.4173   999.8997 
26   80 
54.42817   999.7028 
26   80 
54.42823   999.7028 
26   80 
54.42817   999.7038 
26   80 
54.44529   999.1816 
26   80 
54.44535   999.1816 
26   80 
54.44529   999.1826 
26   80 
54.47345   997.7638 
26   80 
54.47351   997.7638 
26   80 
54.47345   997.7648 
26   80 
54.51938   993.989 
26   80 
54.51943   993.989 
26   80 
54.51938   993.99 
26   80 
54.59614   983.8509 
26   80 
54.5962   983.8509 
26   80 
54.59614   983.8518 
26   80 
54.73068   956.056 
26   80 
54.73073   956.056 
26   80 
54.73068   956.057 
26   80 
55.00355   873.0754 
26   80 
55.0036   873.0754 
26   80 
55.00355   873.0763 
26   80 
56.02025   482.1398 
26   80 
56.0203   482.1398 
26   80 
56.02025   482.1402 
Fit Mean:  59.80919  Size:  -938.7807  Code:  1 
Try Mean:  54.00122  Size:  100 
26   80 
54.00122   100 
26   80 
54.00122   100 
26   80 
54.00128   100 
26   80 
54.00122   100.0001 
26   80 
54.00136   99.99998 
26   80 
54.00141   99.99998 
26   80 
54.00136   100.0001 
26   80 
54.62474   99.79891 
26   80 
54.62479   99.79891 
26   80 
54.62474   99.79901 
26   80 
54.64987   99.68571 
26   80 
54.64992   99.68571 
26   80 
54.64987   99.68581 
26   80 
55.09756   95.78415 
26   80 
55.09762   95.78415 
26   80 
55.09756   95.78425 
26   80 
55.66694   86.86204 
26   80 
55.667   86.86204 
26   80 
55.66694   86.86212 
26   80 
57.59984   44.02967 
26   80 
57.5999   44.02967 
26   80 
57.59984   44.02971 
Fit Mean:  59.75762  Size:  -8.000734  Code:  1 
Try Mean:  54.00122  Size:  10 
26   80 
54.00122   10 
26   80 
54.00122   10 
26   80 
54.00128   10 
26   80 
54.00122   10.00001 
26   80 
54.00147   10.00031 
26   80 
54.00153   10.00031 
26   80 
54.00147   10.00032 
26   80 
57.49931   15.83123 
26   80 
57.49937   15.83123 
26   80 
57.49931   15.83125 
26   80 
56.48034   17.85473 
26   80 
56.4804   17.85473 
26   80 
56.48034   17.85475 
26   80 
54.582   23.80801 
26   80 
54.58205   23.80801 
26   80 
54.582   23.80803 
26   80 
55.29756   24.78829 
26   80 
55.29761   24.78829 
26   80 
55.29756   24.78831 
26   80 
55.33084   26.38158 
26   80 
55.33089   26.38158 
26   80 
55.33084   26.3816 
26   80 
55.25919   27.23234 
26   80 
55.25924   27.23234 
26   80 
55.25919   27.23237 
26   80 
55.24846   27.38297 
26   80 
55.24852   27.38297 
26   80 
55.24846   27.383 
26   80 
55.24865   27.39121 
26   80 
55.24871   27.39121 
26   80 
55.24865   27.39124 
Fit Mean:  55.24865  Size:  27.39121  Code:  1 
> 
> cat("Final Fit Mean: ", nb_fit_mu, " Size: ", nb_fit_size, " Code: ", nb_fit$code, " Try Size: ", try_size, "\n")
Final Fit Mean:  55.24865  Size:  27.39121  Code:  1  Try Size:  10 
> 
> ## Fit failed = reset parameters so graphing and output code can recognize this
> if ((nb_fit_mu < 0) || (nb_fit_size < 0) || (nb_fit$code != 1))
+ {
+   nb_fit_mu = 0
+   nb_fit_size = 0
+ }
> 
> 
> ## things can go wrong with fitting and we can still end up with invalid values
> 
> fit_nb = c()
> included_fract = 0
> if (nb_fit_mu > 0)
+ {
+   end_fract = pnbinom(end_i_for_fits, mu = nb_fit_mu, size=nb_fit_size)
+   start_fract = pnbinom(start_i_for_fits, mu = nb_fit_mu, size=nb_fit_size)
+   included_fract = end_fract-start_fract;
+ 
+   if (included_fract >= 0.01) {
+ 
+     ## Adjust so that we are back in full coords before making fit!!
+     if (num_per_bin > 1) 
+     {
+       nb_fit_mu = nb_fit_mu * num_per_bin
+     }
+     fit_nb = dnbinom(0:max(X$coverage), mu = nb_fit_mu, size=nb_fit_size)*inner_total/included_fract;
+   }
+ }
> 
> ## If an insufficient amount of fit was included, then invalidate it
> if (included_fract < 0.01)
+ {
+   nb_fit_mu = 0
+   nb_fit_size = 0
+ }
> 
> f_p <- function(par) {
+ 
+   lambda = par[1];
+ 
+   if (lambda <= 0)
+   {
+     return(0);
+   }
+   
+ 	total <- 0;
+ 	for (i in start_i_for_fits:end_i_for_fits)
+ 	{	
+     #cat(i, " ", lambda, "\n");
+ 		dist[i] <- dpois(i, lambda=lambda);
+ 		total <- total + dist[i] 
+ 	}
+ 	#print (total)
+ 
+  	l <- 0;
+ 	for (i in start_i_for_fits:end_i_for_fits)
+ 	{
+ 		l <- l + ((X.for.fits[i]/inner_total)-(dist[i]/total))^2;
+ 	}
+ 	return(l);
+ }
> 
> 
> ## Fit Poisson 
> ## - allow fit to fail and set all params to zero/empty if that is the case
> 
> p_fit = NULL
> try(suppressWarnings(p_fit<-nlm(f_p, c(m), print.level=this.print.level)))
> 
> fit_p = c()
> if (!is.null(p_fit) && (p_fit$estimate[1] > 0))
+ {
+   #print (nb_fit$estimate[1])
+   p_fit_lambda = p_fit$estimate[1];
+   #print(0:max(X$coverage))
+ 
+   end_fract = ppois(end_i_for_fits, lambda = p_fit_lambda)
+   start_fract = ppois(start_i_for_fits, lambda = p_fit_lambda)
+   included_fract = end_fract-start_fract;
+ 
+   ## Adjust so that we are back in full coords before making fit!!
+   if (num_per_bin > 1) 
+   {
+     p_fit_lambda = p_fit_lambda * num_per_bin
+   }
+   fit_p<-dpois(0:max(X$coverage), lambda = p_fit_lambda)*inner_total/included_fract;
+ }
> 
> 
> ## Graphing
> ##
> ## don't graph very high values with very little coverage
> i<-max_i
> while (i <= length(X$n) && X$n[i]>0.01*max_n)
+ {		
+ 	i <- i+1;
+ }
> graph_end_i <-i
> 
> ## Ths leaves enough room to the right of the peak for the legend
> graph_end_i = max(floor(2.2 * max_i), graph_end_i);
> 
> ## graphics settings
> my_pch = 21
> my_col = "black";
> my_col_censored = "red";
> 
> if (pdf_output == 0) {
+ 	## units = "px", taa=4, gaa=2 NOT compatible with earlier R versions!
+ 	bitmap(plot_file, height=6, width=7, type = "png16m", res = 72, pointsize=18)
+ } else {
+ 	pdf(plot_file, height=6, width=7)
+ }
> 
> par(mar=c(5.5,7.5,3,1.5));
> 
> max_y = 0
> if (plot_poisson) {
+ 	max_y = max(X$n, fit_p, fit_nb)
+ } else {
+ 	max_y = max(X$n, fit_nb)
+ }
> 
> plot(0:10, 0:10, type="n", lty="solid", ylim=c(0, max_y)*1.05, xlim=c(0, graph_end_i), lwd=1, xaxs="i", yaxs="i", axes=F, las=1, main="Coverage Distribution at Unique-Only Positions", xlab="Coverage depth (reads)", ylab="", cex.lab=1.2, cex.axis=1.2)
> 
> mtext(side = 2, text = "Number of reference positions", line = 5.5, cex=1.2)
> 
> sciNotation <- function(x, digits = 1) {
+     if (length(x) > 1) {
+         return(append(sciNotation(x[1]), sciNotation(x[-1])))     
+ 	} 
+     if (!x) return(0) 
+ 
+ 	exponent <- floor(log10(x)) 
+     base <- round(x / 10^exponent, digits)     
+ 	as.expression(substitute(base %*% 10^exponent, list(base = base, exponent = exponent))) 
+ }
> 
> #axis(2, cex.lab=1.2, las=1, cex.axis=1.2, labels=T, at=(0:6)*50000)
> axis(2, cex.lab=1.2, las=1, cex.axis=1.2, at = axTicks(2), labels = sciNotation(axTicks(2), 1))
> axis(1, cex.lab=1.2, cex.axis=1.2, labels=T)
> box()
> 
> #graph the coverage as points
> fit_data <- subset(X, (coverage>=start_i) & (coverage<=end_i) );
> points(fit_data$coverage, fit_data$n, pch=my_pch, col=my_col, bg="white", cex=1.2)
> 
> #graph the censored coverage as red points
> cat(start_i, " ", end_i, "\n", sep="")
26 80
> 
> censored_data <- subset(X, (coverage<start_i) | (coverage>end_i) );
> points(censored_data$coverage, censored_data$n, pch=my_pch, col=my_col_censored, bg="white", cex=1.2)
> 
> #graph the poisson fit IF REQUESTED
> if (plot_poisson) {
+ 	lines(0:max(X$coverage), fit_p, lwd=3, lty="22", col="black");
+ }
> 
> #graph the negative binomial fit
> if (nb_fit_mu > 0) {
+   lines(0:max(X$coverage), fit_nb, lwd=3, col="black");
+ }
> 
> if (plot_poisson) {
+ 	legend("topright", c("Coverage distribution", "Censored data", "Negative binomial", "Poisson"), lty=c("blank","blank","solid","22"), lwd=c(1,1,2,2), pch=c(my_pch, my_pch, -1, -1), col=c("black", "red", "black", "black"), bty="n")
+ } else {
+ 	legend("topright", c("Coverage distribution", "Censored data", "Negative binomial"), lty=c("blank","blank","solid"), lwd=c(1,1,2), pch=c(my_pch, my_pch, -1), col=c("black", "red", "black"), bty="n")
+ }
> 
> dev.off()
pdf 
  2 
> 
> ## Fit the marginal value that we use for propagating deletions
> 
> if (nb_fit_mu > 0) {
+   cat(nb_fit_size, " ", nb_fit_mu, "\n")
+   deletion_propagation_coverage = suppressWarnings(qnbinom(deletion_propagation_pr_cutoff, size = nb_fit_size, mu = nb_fit_mu))
+ } else {
+   cat("Fallback to calculating off an estimate of just variance = mu + mu^2/size\n")
+   size_estimate = (1/(v-m))*(m*m)
+   cat("Mu estimate=", m," Size estimate =", size_estimate, "\n")
+   deletion_propagation_coverage = suppressWarnings(qnbinom(deletion_propagation_pr_cutoff, size = size_estimate, mu = m))
+   if (is.na(deletion_propagation_coverage) || is.nan(deletion_propagation_coverage) || (deletion_propagation_coverage < 1)) {
+     cat("Double fallback to calculating as just 10% of the mean\n")
+     deletion_propagation_coverage = m * 0.1
+   }
+ }
27.39121   55.24865 
> 
> #Don't allow one read to indicate non-deleted regions
> if (deletion_propagation_coverage < 1) {
+     deletion_propagation_coverage = 1
+ }
> 
> #This works fine with the negative values
> #If we have both low fit coverage and low straight average coverage then we're deleted...
> if ( (nb_fit_mu <= 3) && (m <= 3) ) {
+   deletion_propagation_coverage = -1
+ }
> 
> #print out statistics
> 
> print(nb_fit_size);
[1] 27.39121
> print(nb_fit_mu);
[1] 55.24865
> 
> print(m)
[1] 55.06911
> print(v)
[1] 166.1561
> print(D)
[1] 3.017229
> 
> print(deletion_propagation_coverage)
[1] 15
> 
> warnings()
NULL
>

**Comment by jeffreybarrick** [comment]
That's odd. There appears to be no error.

Can you try deleting all of the output and running breseq again?

Also, make sure that you are not running out of hard drive space during the breseq run.

**Comment by RachelHick** [comment]
Hello again, 
I'm still running into the same problem and not quite sure how to resolve it. 

Error running command:
[system] R --vanilla < /usr/local/bin/../share/breseq//coverage_distribution.r > REL8593M-no-filters/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log distribution_file=REL8593M-no-filters/03_candidate_junctions/0.unique_only_coverage_distribution.tab plot_file=REL8593M-no-filters/03_candidate_junctions/0.coverage.pdf deletion_propagation_pr_cutoff=2.32374e-05
Result code: 256
FILE: ./libbreseq/common.h   LINE: 1479

So any tips would be great!!!

**Comment by jeffreybarrick** [comment]
Hi Rachel,

Here are two options:

1) Try downloading and installing a fresh version of R (the *.pkg version for your OS):
https://cran.r-project.org/bin/macosx/

2) Contact me at the email in the _breseq_ header and share your input files with me so that I can determine whether this is a problem within _breseq_ or with your install.
